namespace RestChild.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class LastUpdateTickMigration : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.AccessRight", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.AccountRights", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Account", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.AccountRoles", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Organization", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.LimitOnOrganization", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.HistoryLink", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.History", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.SignInfo", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.LimitOnVedomstvo", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.LimitOnOrganizationRequest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.PlaceOfRest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Country", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.StateMachineState", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.StateMachineAction", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.StateMachineFromStatus", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.StateMachine", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.YearOfRest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TimeOfRest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.GroupedTimeOfRest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TypeOfRest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.DeclineReason", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.RequestFileType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TypeOfGroupCheck", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Tour", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Applicant", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ApplicantType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Bout", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.AdministratorTour", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.DocumentType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ForeginPassport", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Counselors", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ClothingSize", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CouncelorComment", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Child", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Address", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.BtiAddress", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.BtiDistrict", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.BtiRegion", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.BtiStreet", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ExchangeBaseRegistry", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ExchangeBaseRegistryType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.BenefitApproveType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.BenefitGroupInvalid", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.BenefitType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Calculation", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.AddonServicesLink", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.AddonServices", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.AddonServicesPaymentType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Hotels", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Accommodation", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.AccommodationChildren", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.City", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.HotelContactPerson", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.DiningOptions", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.FileHotel", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.FileType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TypeOfRooms", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TypeOfRoomsFiles", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.FunctioningType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.HotelPlacement", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.HotelType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.RoomRates", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.RoomRatesPrice", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.AddonServicesPhoto", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TypeOfService", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Request", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Agent", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.AttendantType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.DiscountCard", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Discount", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.RequestFile", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.RequestInformationVoucher", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.RequestInformationVoucherAttendant", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TypeRequestInformationVoucher", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.OfferInRequest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Source", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Status", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.StatusAction", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.SubjectOfRest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.LinkToFile", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.FileOrLink", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Payment", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Ticket", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.DirectoryFlights", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Contract", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TypeOfTransport", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TypeOfCalculation", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ListOfChilds", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ListOfChildsCategory", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ChildIncludeExcludeReason", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.LinkToPeople", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.NotNeedTicketReason", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Party", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TransportInfo", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TypeOfLinkPeople", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.School", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.StatusByChild", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TourVolume", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TypeOfRestriction", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorCource", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorPractice", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorFile", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorHighSchool", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.MatrialStatus", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.MilitaryDuty", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.PedParty", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TrainingCounselorsResult", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorTestAnswer", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorTest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorTestQuestion", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorTestQuestionType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorTestAnswerVariant", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TrainingCounselorsTest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TrainingCounselorsResultStatus", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TrainingCounselors", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TrainingCounselorsPlace", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TrainingCounselorsTime", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TrainingCounselorsType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorSkill", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Skill", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.SkillsGroup", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.SkillVocabulary", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.StateDistrict", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorsStopListReason", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ResponsibilityForTask", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorTaskExecutorType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TieColor", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TypeOfEducation", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.BoutAttendant", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.BoutJournal", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.BoutJournalType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.BoutJournalFile", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.FileOfTour", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TourPrice", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Role", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.AnalyticsViewRow", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.AnalyticsViewRowType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.Booking", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorTask", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorTaskCommentary", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorTaskFile", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.CounselorTaskReportFile", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ExchangeUTS", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ExcludeDays", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.HistoryInteragencyRequest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.InteragencyRequest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.StatusInteragencyRequest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.HistoryRequest", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.InteragencyRequestBenefitType", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.InteragencyRequestResult", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.StatusResult", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ReportRowData", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ReportTableHead", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ReportTable", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ReportSheet", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.ReportTableRow", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.SendEmailAndSms", "LastUpdateTick", c => c.Long(nullable: false));
            AddColumn("dbo.TypeOfRestBenefitRestriction", "LastUpdateTick", c => c.Long(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.TypeOfRestBenefitRestriction", "LastUpdateTick");
            DropColumn("dbo.SendEmailAndSms", "LastUpdateTick");
            DropColumn("dbo.ReportTableRow", "LastUpdateTick");
            DropColumn("dbo.ReportSheet", "LastUpdateTick");
            DropColumn("dbo.ReportTable", "LastUpdateTick");
            DropColumn("dbo.ReportTableHead", "LastUpdateTick");
            DropColumn("dbo.ReportRowData", "LastUpdateTick");
            DropColumn("dbo.StatusResult", "LastUpdateTick");
            DropColumn("dbo.InteragencyRequestResult", "LastUpdateTick");
            DropColumn("dbo.InteragencyRequestBenefitType", "LastUpdateTick");
            DropColumn("dbo.HistoryRequest", "LastUpdateTick");
            DropColumn("dbo.StatusInteragencyRequest", "LastUpdateTick");
            DropColumn("dbo.InteragencyRequest", "LastUpdateTick");
            DropColumn("dbo.HistoryInteragencyRequest", "LastUpdateTick");
            DropColumn("dbo.ExcludeDays", "LastUpdateTick");
            DropColumn("dbo.ExchangeUTS", "LastUpdateTick");
            DropColumn("dbo.CounselorTaskReportFile", "LastUpdateTick");
            DropColumn("dbo.CounselorTaskFile", "LastUpdateTick");
            DropColumn("dbo.CounselorTaskCommentary", "LastUpdateTick");
            DropColumn("dbo.CounselorTask", "LastUpdateTick");
            DropColumn("dbo.Booking", "LastUpdateTick");
            DropColumn("dbo.AnalyticsViewRowType", "LastUpdateTick");
            DropColumn("dbo.AnalyticsViewRow", "LastUpdateTick");
            DropColumn("dbo.Role", "LastUpdateTick");
            DropColumn("dbo.TourPrice", "LastUpdateTick");
            DropColumn("dbo.FileOfTour", "LastUpdateTick");
            DropColumn("dbo.BoutJournalFile", "LastUpdateTick");
            DropColumn("dbo.BoutJournalType", "LastUpdateTick");
            DropColumn("dbo.BoutJournal", "LastUpdateTick");
            DropColumn("dbo.BoutAttendant", "LastUpdateTick");
            DropColumn("dbo.TypeOfEducation", "LastUpdateTick");
            DropColumn("dbo.TieColor", "LastUpdateTick");
            DropColumn("dbo.CounselorTaskExecutorType", "LastUpdateTick");
            DropColumn("dbo.ResponsibilityForTask", "LastUpdateTick");
            DropColumn("dbo.CounselorsStopListReason", "LastUpdateTick");
            DropColumn("dbo.StateDistrict", "LastUpdateTick");
            DropColumn("dbo.SkillVocabulary", "LastUpdateTick");
            DropColumn("dbo.SkillsGroup", "LastUpdateTick");
            DropColumn("dbo.Skill", "LastUpdateTick");
            DropColumn("dbo.CounselorSkill", "LastUpdateTick");
            DropColumn("dbo.TrainingCounselorsType", "LastUpdateTick");
            DropColumn("dbo.TrainingCounselorsTime", "LastUpdateTick");
            DropColumn("dbo.TrainingCounselorsPlace", "LastUpdateTick");
            DropColumn("dbo.TrainingCounselors", "LastUpdateTick");
            DropColumn("dbo.TrainingCounselorsResultStatus", "LastUpdateTick");
            DropColumn("dbo.TrainingCounselorsTest", "LastUpdateTick");
            DropColumn("dbo.CounselorTestAnswerVariant", "LastUpdateTick");
            DropColumn("dbo.CounselorTestQuestionType", "LastUpdateTick");
            DropColumn("dbo.CounselorTestQuestion", "LastUpdateTick");
            DropColumn("dbo.CounselorTest", "LastUpdateTick");
            DropColumn("dbo.CounselorTestAnswer", "LastUpdateTick");
            DropColumn("dbo.TrainingCounselorsResult", "LastUpdateTick");
            DropColumn("dbo.PedParty", "LastUpdateTick");
            DropColumn("dbo.MilitaryDuty", "LastUpdateTick");
            DropColumn("dbo.MatrialStatus", "LastUpdateTick");
            DropColumn("dbo.CounselorHighSchool", "LastUpdateTick");
            DropColumn("dbo.CounselorFile", "LastUpdateTick");
            DropColumn("dbo.CounselorPractice", "LastUpdateTick");
            DropColumn("dbo.CounselorCource", "LastUpdateTick");
            DropColumn("dbo.TypeOfRestriction", "LastUpdateTick");
            DropColumn("dbo.TourVolume", "LastUpdateTick");
            DropColumn("dbo.StatusByChild", "LastUpdateTick");
            DropColumn("dbo.School", "LastUpdateTick");
            DropColumn("dbo.TypeOfLinkPeople", "LastUpdateTick");
            DropColumn("dbo.TransportInfo", "LastUpdateTick");
            DropColumn("dbo.Party", "LastUpdateTick");
            DropColumn("dbo.NotNeedTicketReason", "LastUpdateTick");
            DropColumn("dbo.LinkToPeople", "LastUpdateTick");
            DropColumn("dbo.ChildIncludeExcludeReason", "LastUpdateTick");
            DropColumn("dbo.ListOfChildsCategory", "LastUpdateTick");
            DropColumn("dbo.ListOfChilds", "LastUpdateTick");
            DropColumn("dbo.TypeOfCalculation", "LastUpdateTick");
            DropColumn("dbo.TypeOfTransport", "LastUpdateTick");
            DropColumn("dbo.Contract", "LastUpdateTick");
            DropColumn("dbo.DirectoryFlights", "LastUpdateTick");
            DropColumn("dbo.Ticket", "LastUpdateTick");
            DropColumn("dbo.Payment", "LastUpdateTick");
            DropColumn("dbo.FileOrLink", "LastUpdateTick");
            DropColumn("dbo.LinkToFile", "LastUpdateTick");
            DropColumn("dbo.SubjectOfRest", "LastUpdateTick");
            DropColumn("dbo.StatusAction", "LastUpdateTick");
            DropColumn("dbo.Status", "LastUpdateTick");
            DropColumn("dbo.Source", "LastUpdateTick");
            DropColumn("dbo.OfferInRequest", "LastUpdateTick");
            DropColumn("dbo.TypeRequestInformationVoucher", "LastUpdateTick");
            DropColumn("dbo.RequestInformationVoucherAttendant", "LastUpdateTick");
            DropColumn("dbo.RequestInformationVoucher", "LastUpdateTick");
            DropColumn("dbo.RequestFile", "LastUpdateTick");
            DropColumn("dbo.Discount", "LastUpdateTick");
            DropColumn("dbo.DiscountCard", "LastUpdateTick");
            DropColumn("dbo.AttendantType", "LastUpdateTick");
            DropColumn("dbo.Agent", "LastUpdateTick");
            DropColumn("dbo.Request", "LastUpdateTick");
            DropColumn("dbo.TypeOfService", "LastUpdateTick");
            DropColumn("dbo.AddonServicesPhoto", "LastUpdateTick");
            DropColumn("dbo.RoomRatesPrice", "LastUpdateTick");
            DropColumn("dbo.RoomRates", "LastUpdateTick");
            DropColumn("dbo.HotelType", "LastUpdateTick");
            DropColumn("dbo.HotelPlacement", "LastUpdateTick");
            DropColumn("dbo.FunctioningType", "LastUpdateTick");
            DropColumn("dbo.TypeOfRoomsFiles", "LastUpdateTick");
            DropColumn("dbo.TypeOfRooms", "LastUpdateTick");
            DropColumn("dbo.FileType", "LastUpdateTick");
            DropColumn("dbo.FileHotel", "LastUpdateTick");
            DropColumn("dbo.DiningOptions", "LastUpdateTick");
            DropColumn("dbo.HotelContactPerson", "LastUpdateTick");
            DropColumn("dbo.City", "LastUpdateTick");
            DropColumn("dbo.AccommodationChildren", "LastUpdateTick");
            DropColumn("dbo.Accommodation", "LastUpdateTick");
            DropColumn("dbo.Hotels", "LastUpdateTick");
            DropColumn("dbo.AddonServicesPaymentType", "LastUpdateTick");
            DropColumn("dbo.AddonServices", "LastUpdateTick");
            DropColumn("dbo.AddonServicesLink", "LastUpdateTick");
            DropColumn("dbo.Calculation", "LastUpdateTick");
            DropColumn("dbo.BenefitType", "LastUpdateTick");
            DropColumn("dbo.BenefitGroupInvalid", "LastUpdateTick");
            DropColumn("dbo.BenefitApproveType", "LastUpdateTick");
            DropColumn("dbo.ExchangeBaseRegistryType", "LastUpdateTick");
            DropColumn("dbo.ExchangeBaseRegistry", "LastUpdateTick");
            DropColumn("dbo.BtiStreet", "LastUpdateTick");
            DropColumn("dbo.BtiRegion", "LastUpdateTick");
            DropColumn("dbo.BtiDistrict", "LastUpdateTick");
            DropColumn("dbo.BtiAddress", "LastUpdateTick");
            DropColumn("dbo.Address", "LastUpdateTick");
            DropColumn("dbo.Child", "LastUpdateTick");
            DropColumn("dbo.CouncelorComment", "LastUpdateTick");
            DropColumn("dbo.ClothingSize", "LastUpdateTick");
            DropColumn("dbo.Counselors", "LastUpdateTick");
            DropColumn("dbo.ForeginPassport", "LastUpdateTick");
            DropColumn("dbo.DocumentType", "LastUpdateTick");
            DropColumn("dbo.AdministratorTour", "LastUpdateTick");
            DropColumn("dbo.Bout", "LastUpdateTick");
            DropColumn("dbo.ApplicantType", "LastUpdateTick");
            DropColumn("dbo.Applicant", "LastUpdateTick");
            DropColumn("dbo.Tour", "LastUpdateTick");
            DropColumn("dbo.TypeOfGroupCheck", "LastUpdateTick");
            DropColumn("dbo.RequestFileType", "LastUpdateTick");
            DropColumn("dbo.DeclineReason", "LastUpdateTick");
            DropColumn("dbo.TypeOfRest", "LastUpdateTick");
            DropColumn("dbo.GroupedTimeOfRest", "LastUpdateTick");
            DropColumn("dbo.TimeOfRest", "LastUpdateTick");
            DropColumn("dbo.YearOfRest", "LastUpdateTick");
            DropColumn("dbo.StateMachine", "LastUpdateTick");
            DropColumn("dbo.StateMachineFromStatus", "LastUpdateTick");
            DropColumn("dbo.StateMachineAction", "LastUpdateTick");
            DropColumn("dbo.StateMachineState", "LastUpdateTick");
            DropColumn("dbo.Country", "LastUpdateTick");
            DropColumn("dbo.PlaceOfRest", "LastUpdateTick");
            DropColumn("dbo.LimitOnOrganizationRequest", "LastUpdateTick");
            DropColumn("dbo.LimitOnVedomstvo", "LastUpdateTick");
            DropColumn("dbo.SignInfo", "LastUpdateTick");
            DropColumn("dbo.History", "LastUpdateTick");
            DropColumn("dbo.HistoryLink", "LastUpdateTick");
            DropColumn("dbo.LimitOnOrganization", "LastUpdateTick");
            DropColumn("dbo.Organization", "LastUpdateTick");
            DropColumn("dbo.AccountRoles", "LastUpdateTick");
            DropColumn("dbo.Account", "LastUpdateTick");
            DropColumn("dbo.AccountRights", "LastUpdateTick");
            DropColumn("dbo.AccessRight", "LastUpdateTick");
        }
    }
}
