// <auto-generated />
namespace RestChild.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Lok20174FlagInChainMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lok20174FlagInChainMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201702011531289_Lok20174FlagInChainMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
