// <auto-generated />
namespace RestChild.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Facilities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Facilities));
        
        string IMigrationMetadata.Id
        {
            get { return "202110280712294_Facilities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
