//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

//
// This source code was auto-generated by xsd, Version=4.7.3081.0.
//

namespace RestChild.Comon.Exchange.Passport
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://asur/fms/")]
    [System.Xml.Serialization.XmlRootAttribute("OutPassport", Namespace = "http://asur/fms/", IsNullable = false)]
    public partial class OutPassportType
    {

        private string stateField;

        private string sNILSField;

        private string firstNameField;

        private string lastNameField;

        private string patronymicField;

        private string birthDateField;

        private string commentField;

        private DocumentFMSType[] documentsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string State
        {
            get { return this.stateField; }
            set { this.stateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SNILS
        {
            get { return this.sNILSField; }
            set { this.sNILSField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FirstName
        {
            get { return this.firstNameField; }
            set { this.firstNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastName
        {
            get { return this.lastNameField; }
            set { this.lastNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Patronymic
        {
            get { return this.patronymicField; }
            set { this.patronymicField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BirthDate
        {
            get { return this.birthDateField; }
            set { this.birthDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comment
        {
            get { return this.commentField; }
            set { this.commentField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DocumentFMS",
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DocumentFMSType[] Documents
        {
            get { return this.documentsField; }
            set { this.documentsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://asur/fms/")]
    public partial class DocumentFMSType
    {

        private string numberField;

        private string nameDocumentField;

        private string codeDocumentField;

        private string seriesField;

        private string issueField;

        private string issueDateField;

        private string statusField;

        private string statusCodeField;

        private string invalidityReasonCodeField;

        private string invalidityReasonField;

        private string invaliditySinceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Number
        {
            get { return this.numberField; }
            set { this.numberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NameDocument
        {
            get { return this.nameDocumentField; }
            set { this.nameDocumentField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodeDocument
        {
            get { return this.codeDocumentField; }
            set { this.codeDocumentField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Series
        {
            get { return this.seriesField; }
            set { this.seriesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Issue
        {
            get { return this.issueField; }
            set { this.issueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IssueDate
        {
            get { return this.issueDateField; }
            set { this.issueDateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status
        {
            get { return this.statusField; }
            set { this.statusField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StatusCode
        {
            get { return this.statusCodeField; }
            set { this.statusCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InvalidityReasonCode
        {
            get { return this.invalidityReasonCodeField; }
            set { this.invalidityReasonCodeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InvalidityReason
        {
            get { return this.invalidityReasonField; }
            set { this.invalidityReasonField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified,
            IsNullable = true)]
        public string InvaliditySince
        {
            get { return this.invaliditySinceField; }
            set { this.invaliditySinceField = value; }
        }
    }
}
