-- Формирование справочника стран

INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (895, '895', 'АБХАЗИЯ', 'Республика Абхазия', 'AB', 'ABH')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (036, '036', 'АВСТРАЛИЯ', 'Австралия', 'AU', 'AUS')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (040, '040', 'АВСТРИЯ', 'Австрийская Республика', 'AT', 'AUT')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (031, '031', 'АЗЕРБАЙДЖАН', 'Республика Азербайджан', 'AZ', 'AZE')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (008, '008', 'АЛБАНИЯ', 'Республика Албания', 'AL', 'ALB')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (012, '012', 'АЛЖИР', 'Алжирская Народная Демократическая Республика', 'DZ', 'DZA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (016, '016', 'АМЕРИКАНСКОЕ САМОА', 'Американское Самоа', 'AS', 'ASM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (660, '660', 'АНГИЛЬЯ', 'Ангилья', 'AI', 'AIA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (024, '024', 'АНГОЛА', 'Республика Ангола', 'AO', 'AGO')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (020, '020', 'АНДОРРА', 'Княжество Андорра', 'AD', 'AND')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (010, '010', 'АНТАРКТИДА', 'Антарктида', 'AQ', 'ATA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (028, '028', 'АНТИГУА И БАРБУДА', 'Антигуа И Барбуда', 'AG', 'ATG')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (032, '032', 'АРГЕНТИНА', 'Аргентинская Республика', 'AR', 'ARG')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (051, '051', 'АРМЕНИЯ', 'Республика Армения', 'AM', 'ARM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (533, '533', 'АРУБА', 'Аруба', 'AW', 'ABW')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (004, '004', 'АФГАНИСТАН', 'Переходное Исламское Государство Афганистан', 'AF', 'AFG')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (044, '044', 'БАГАМЫ', 'Содружество Багамы', 'BS', 'BHS')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (050, '050', 'БАНГЛАДЕШ', 'Народная Республика Бангладеш', 'BD', 'BGD')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (052, '052', 'БАРБАДОС', 'Барбадос', 'BB', 'BRB')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (048, '048', 'БАХРЕЙН', 'Королевство Бахрейн', 'BH', 'BHR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (112, '112', 'БЕЛАРУСЬ', 'Республика Беларусь', 'BY', 'BLR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (084, '084', 'БЕЛИЗ', 'Белиз', 'BZ', 'BLZ')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (056, '056', 'БЕЛЬГИЯ', 'Королевство Бельгии', 'BE', 'BEL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (204, '204', 'БЕНИН', 'Республика Бенин', 'BJ', 'BEN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (060, '060', 'БЕРМУДЫ', 'Бермуды', 'BM', 'BMU')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (100, '100', 'БОЛГАРИЯ', 'Республика Болгария', 'BG', 'BGR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (068, '068', 'БОЛИВИЯ, МНОГОНАЦИОНАЛЬНОЕ ГОСУДАРСТВО', 'Многонациональное Государство Боливия', 'BO', 'BOL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (535, '535', 'БОНЭЙР, СИНТ-ЭСТАТИУС И САБА', 'Бонэйр, Синт-Эстатиус И Саба', 'BQ', 'BES')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (070, '070', 'БОСНИЯ И ГЕРЦЕГОВИНА', 'Босния И Герцеговина', 'BA', 'BIH')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (072, '072', 'БОТСВАНА', 'Республика Ботсвана', 'BW', 'BWA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (076, '076', 'БРАЗИЛИЯ', 'Федеративная Республика Бразилия', 'BR', 'BRA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (086, '086', 'БРИТАНСКАЯ ТЕРРИТОРИЯ В ИНДИЙСКОМ ОКЕАНЕ', 'Британская Территория В Индийском Океане', 'IO', 'IOT')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (096, '096', 'БРУНЕЙ-ДАРУССАЛАМ', 'Бруней-Даруссалам', 'BN', 'BRN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (854, '854', 'БУРКИНА-ФАСО', 'Буркина-Фасо', 'BF', 'BFA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (108, '108', 'БУРУНДИ', 'Республика Бурунди', 'BI', 'BDI')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (064, '064', 'БУТАН', 'Королевство Бутан', 'BT', 'BTN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (548, '548', 'ВАНУАТУ', 'Республика Вануату', 'VU', 'VUT')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (348, '348', 'ВЕНГРИЯ', 'Венгрия', 'HU', 'HUN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (862, '862', 'ВЕНЕСУЭЛА БОЛИВАРИАНСКАЯ РЕСПУБЛИКА', 'Боливарианская Республика Венесуэла', 'VE', 'VEN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (092, '092', 'ВИРГИНСКИЕ ОСТРОВА, БРИТАНСКИЕ', 'Британские Виргинские острова', 'VG', 'VGB')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (850, '850', 'ВИРГИНСКИЕ ОСТРОВА, США', 'Виргинские острова Соединенных Штатов', 'VI', 'VIR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (626, '626', 'ТИМОР-ЛЕСТЕ', 'Демократическая Республика Тимор-Лесте', 'TL', 'TLS')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (704, '704', 'ВЬЕТНАМ', 'Социалистическая Республика Вьетнам', 'VN', 'VNM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (266, '266', 'ГАБОН', 'Габонская Республика', 'GA', 'GAB')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (332, '332', 'ГАИТИ', 'Республика Гаити', 'HT', 'HTI')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (328, '328', 'ГАЙАНА', 'Республика Гайана', 'GY', 'GUY')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (270, '270', 'ГАМБИЯ', 'Республика Гамбия', 'GM', 'GMB')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (288, '288', 'ГАНА', 'Республика Гана', 'GH', 'GHA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (312, '312', 'ГВАДЕЛУПА', 'Гваделупа', 'GP', 'GLP')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (320, '320', 'ГВАТЕМАЛА', 'Республика Гватемала', 'GT', 'GTM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (324, '324', 'ГВИНЕЯ', 'Гвинейская Республика', 'GN', 'GIN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (624, '624', 'ГВИНЕЯ-БИСАУ', 'Республика Гвинея-Бисау', 'GW', 'GNB')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (276, '276', 'ГЕРМАНИЯ', 'Федеративная Республика Германия', 'DE', 'DEU')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (831, '831', 'ГЕРНСИ', 'Гернси', 'GG', 'GGY')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (292, '292', 'ГИБРАЛТАР', 'Гибралтар', 'GI', 'GIB')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (340, '340', 'ГОНДУРАС', 'Республика Гондурас', 'HN', 'HND')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (344, '344', 'ГОНКОНГ', 'Специальный административный регион Китая Гонконг', 'HK', 'HKG')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (308, '308', 'ГРЕНАДА', 'Гренада', 'GD', 'GRD')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (304, '304', 'ГРЕНЛАНДИЯ', 'Гренландия', 'GL', 'GRL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (300, '300', 'ГРЕЦИЯ', 'Греческая Республика', 'GR', 'GRC')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (268, '268', 'ГРУЗИЯ', 'Грузия', 'GE', 'GEO')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (316, '316', 'ГУАМ', 'Гуам', 'GU', 'GUM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (208, '208', 'ДАНИЯ', 'Королевство Дания', 'DK', 'DNK')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (832, '832', 'ДЖЕРСИ', 'Джерси', 'JE', 'JEY')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (262, '262', 'ДЖИБУТИ', 'Республика Джибути', 'DJ', 'DJI')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (212, '212', 'ДОМИНИКА', 'Содружество Доминики', 'DM', 'DMA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (214, '214', 'ДОМИНИКАНСКАЯ РЕСПУБЛИКА', 'Доминиканская Республика', 'DO', 'DOM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (818, '818', 'ЕГИПЕТ', 'Арабская Республика Египет', 'EG', 'EGY')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (894, '894', 'ЗАМБИЯ', 'Республика Замбия', 'ZM', 'ZMB')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (732, '732', 'ЗАПАДНАЯ САХАРА', 'Западная Сахара', 'EH', 'ESH')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (716, '716', 'ЗИМБАБВЕ', 'Республика Зимбабве', 'ZW', 'ZWE')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (376, '376', 'ИЗРАИЛЬ', 'Государство Израиль', 'IL', 'ISR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (356, '356', 'ИНДИЯ', 'Республика Индия', 'IN', 'IND')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (360, '360', 'ИНДОНЕЗИЯ', 'Республика Индонезия', 'ID', 'IDN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (400, '400', 'ИОРДАНИЯ', 'Иорданское Хашимитское Королевство', 'JO', 'JOR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (368, '368', 'ИРАК', 'Республика Ирак', 'IQ', 'IRQ')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (364, '364', 'ИРАН, ИСЛАМСКАЯ РЕСПУБЛИКА', 'Исламская Республика Иран', 'IR', 'IRN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (372, '372', 'ИРЛАНДИЯ', 'Ирландия', 'IE', 'IRL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (352, '352', 'ИСЛАНДИЯ', 'Республика Исландия', 'IS', 'ISL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (724, '724', 'ИСПАНИЯ', 'Королевство Испания', 'ES', 'ESP')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (380, '380', 'ИТАЛИЯ', 'Итальянская Республика', 'IT', 'ITA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (887, '887', 'ЙЕМЕН', 'Йеменская Республика', 'YE', 'YEM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (132, '132', 'КАБО-ВЕРДЕ', 'Республика Кабо-Верде', 'CV', 'CPV')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (398, '398', 'КАЗАХСТАН', 'Республика Казахстан', 'KZ', 'KAZ')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (116, '116', 'КАМБОДЖА', 'Королевство Камбоджа', 'KH', 'KHM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (120, '120', 'КАМЕРУН', 'Республика Камерун', 'CM', 'CMR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (124, '124', 'КАНАДА', 'Канада', 'CA', 'CAN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (634, '634', 'КАТАР', 'Государство Катар', 'QA', 'QAT')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (404, '404', 'КЕНИЯ', 'Республика Кения', 'KE', 'KEN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (196, '196', 'КИПР', 'Республика Кипр', 'CY', 'CYP')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (417, '417', 'КИРГИЗИЯ', 'Киргизская Республика', 'KG', 'KGZ')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (296, '296', 'КИРИБАТИ', 'Республика Кирибати', 'KI', 'KIR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (156, '156', 'КИТАЙ', 'Китайская Народная Республика', 'CN', 'CHN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (166, '166', 'КОКОСОВЫЕ (КИЛИНГ) ОСТРОВА', 'Кокосовые (Килинг) Острова', 'CC', 'CCK')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (170, '170', 'КОЛУМБИЯ', 'Республика Колумбия', 'CO', 'COL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (174, '174', 'КОМОРЫ', 'Союз Коморы', 'KM', 'COM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (178, '178', 'КОНГО', 'Республика Конго', 'CG', 'COG')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (180, '180', 'КОНГО, ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', 'Конго, Демократическая Республика', 'CD', 'COD')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (408, '408', 'КОРЕЯ, НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', 'Корейская Народно-Демократическая Республика', 'KP', 'PRK')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (410, '410', 'КОРЕЯ, РЕСПУБЛИКА', 'Республика Корея', 'KR', 'KOR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (188, '188', 'КОСТА-РИКА', 'Республика Коста-Рика', 'CR', 'CRI')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (384, '384', 'КОТ Д’ИВУАР', 'Республика Кот д’Ивуар', 'CI', 'CIV')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (192, '192', 'КУБА', 'Республика Куба', 'CU', 'CUB')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (414, '414', 'КУВЕЙТ', 'Государство Кувейт', 'KW', 'KWT')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (531, '531', 'КЮРАСАО', 'Кюрасао', 'CW', 'CUW')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (418, '418', 'ЛАОССКАЯ НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА', 'Лаосская Народно-Демократическая Республика', 'LA', 'LAO')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (428, '428', 'ЛАТВИЯ', 'Латвийская Республика', 'LV', 'LVA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (426, '426', 'ЛЕСОТО', 'Королевство Лесото', 'LS', 'LSO')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (430, '430', 'ЛИБЕРИЯ', 'Республика Либерия', 'LR', 'LBR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (422, '422', 'ЛИВАН', 'Ливанская Республика', 'LB', 'LBN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (434, '434', 'ЛИВИЯ', 'Ливия', 'LY', 'LBY')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (440, '440', 'ЛИТВА', 'Литовская Республика', 'LT', 'LTU')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (438, '438', 'ЛИХТЕНШТЕЙН', 'Княжество Лихтенштейн', 'LI', 'LIE')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (442, '442', 'ЛЮКСЕМБУРГ', 'Великое Герцогство Люксембург', 'LU', 'LUX')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (480, '480', 'МАВРИКИЙ', 'Республика Маврикий', 'MU', 'MUS')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (478, '478', 'МАВРИТАНИЯ', 'Исламская Республика Мавритания', 'MR', 'MRT')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (450, '450', 'МАДАГАСКАР', 'Республика Мадагаскар', 'MG', 'MDG')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (175, '175', 'МАЙОТТА', 'Майотта', 'YT', 'MYT')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (446, '446', 'МАКАО', 'Специальный административный регион Китая Макао', 'MO', 'MAC')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (807, '807', 'РЕСПУБЛИКА МАКЕДОНИЯ', 'Республика Македония', 'MK', 'MKD')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (454, '454', 'МАЛАВИ', 'Республика Малави', 'MW', 'MWI')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (458, '458', 'МАЛАЙЗИЯ', 'Малайзия', 'MY', 'MYS')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (466, '466', 'МАЛИ', 'Республика Мали', 'ML', 'MLI')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (581, '581', 'МАЛЫЕ ТИХООКЕАНСКИЕ ОТДАЛЕННЫЕ ОСТРОВА СОЕДИНЕННЫХ ШТАТОВ', 'Малые Тихоокеанские Отдаленные Острова Соединенных Штатов', 'UM', 'UMI')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (462, '462', 'МАЛЬДИВЫ', 'Мальдивская Республика', 'MV', 'MDV')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (470, '470', 'МАЛЬТА', 'Республика Мальта', 'MT', 'MLT')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (504, '504', 'МАРОККО', 'Королевство Марокко', 'MA', 'MAR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (474, '474', 'МАРТИНИКА', 'Мартиника', 'MQ', 'MTQ')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (584, '584', 'МАРШАЛЛОВЫ ОСТРОВА', 'Республика Маршалловы Острова', 'MH', 'MHL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (484, '484', 'МЕКСИКА', 'Мексиканские Соединенные Штаты', 'MX', 'MEX')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (583, '583', 'МИКРОНЕЗИЯ, ФЕДЕРАТИВНЫЕ ШТАТЫ', 'Федеративные Штаты Микронезии', 'FM', 'FSM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (508, '508', 'МОЗАМБИК', 'Республика Мозамбик', 'MZ', 'MOZ')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (498, '498', 'МОЛДОВА, РЕСПУБЛИКА', 'Республика Молдова', 'MD', 'MDA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (492, '492', 'МОНАКО', 'Княжество Монако', 'MC', 'MCO')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (496, '496', 'МОНГОЛИЯ', 'Монголия', 'MN', 'MNG')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (500, '500', 'МОНТСЕРРАТ', 'Монтсеррат', 'MS', 'MSR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (104, '104', 'МЬЯНМА', 'Республика Союза Мьянма', 'MM', 'MMR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (516, '516', 'НАМИБИЯ', 'Республика Намибия', 'NA', 'NAM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (520, '520', 'НАУРУ', 'Республика Науру', 'NR', 'NRU')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (524, '524', 'НЕПАЛ', 'Федеративная Демократическая Республика Непал', 'NP', 'NPL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (562, '562', 'НИГЕР', 'Республика Нигер', 'NE', 'NER')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (566, '566', 'НИГЕРИЯ', 'Федеративная Республика Нигерия', 'NG', 'NGA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (528, '528', 'НИДЕРЛАНДЫ', 'Королевство Нидерландов', 'NL', 'NLD')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (558, '558', 'НИКАРАГУА', 'Республика Никарагуа', 'NI', 'NIC')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (570, '570', 'НИУЭ', 'Ниуэ', 'NU', 'NIU')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (554, '554', 'НОВАЯ ЗЕЛАНДИЯ', 'Новая Зеландия', 'NZ', 'NZL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (540, '540', 'НОВАЯ КАЛЕДОНИЯ', 'Новая Каледония', 'NC', 'NCL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (578, '578', 'НОРВЕГИЯ', 'Королевство Норвегия', 'NO', 'NOR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (784, '784', 'ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ', 'Объединенные Арабские Эмираты', 'AE', 'ARE')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (512, '512', 'ОМАН', 'Султанат Оман', 'OM', 'OMN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (136, '136', 'ОСТРОВА КАЙМАН', 'Острова Кайман', 'KY', 'CYM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (184, '184', 'ОСТРОВА КУКА', 'Острова Кука', 'CK', 'COK')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (796, '796', 'ОСТРОВА ТЕРКС И КАЙКОС', 'Острова Теркс И Кайкос', 'TC', 'TCA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (074, '074', 'ОСТРОВ БУВЕ', 'Остров Буве', 'BV', 'BVT')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (833, '833', 'ОСТРОВ МЭН', 'Остров Мэн', 'IM', 'IMN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (574, '574', 'ОСТРОВ НОРФОЛК', 'Остров Норфолк', 'NF', 'NFK')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (162, '162', 'ОСТРОВ РОЖДЕСТВА', 'Остров Рождества', 'CX', 'CXR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (334, '334', 'ОСТРОВ ХЕРД И ОСТРОВА МАКДОНАЛЬД', 'Остров Херд И Острова Макдональд', 'HM', 'HMD')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (586, '586', 'ПАКИСТАН', 'Исламская Республика Пакистан', 'PK', 'PAK')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (585, '585', 'ПАЛАУ', 'Республика Палау', 'PW', 'PLW')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (275, '275', 'ПАЛЕСТИНА, ГОСУДАРСТВО', 'Государство Палестина', 'PS', 'PSE')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (591, '591', 'ПАНАМА', 'Республика Панама', 'PA', 'PAN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (336, '336', 'ПАПСКИЙ ПРЕСТОЛ (ГОСУДАРСТВО — ГОРОД ВАТИКАН)', 'Папский Престол (Государство — Город Ватикан)', 'VA', 'VAT')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (598, '598', 'ПАПУА-НОВАЯ ГВИНЕЯ', 'Папуа-Новая Гвинея', 'PG', 'PNG')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (600, '600', 'ПАРАГВАЙ', 'Республика Парагвай', 'PY', 'PRY')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (604, '604', 'ПЕРУ', 'Республика Перу', 'PE', 'PER')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (612, '612', 'ПИТКЕРН', 'Питкерн', 'PN', 'PCN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (616, '616', 'ПОЛЬША', 'Республика Польша', 'PL', 'POL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (620, '620', 'ПОРТУГАЛИЯ', 'Португальская Республика', 'PT', 'PRT')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (630, '630', 'ПУЭРТО-РИКО', 'Пуэрто-Рико', 'PR', 'PRI')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (638, '638', 'РЕЮНЬОН', 'Реюньон', 'RE', 'REU')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (643, '643', 'РОССИЯ', 'Российская Федерация', 'RU', 'RUS')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (646, '646', 'РУАНДА', 'Руандийская Республика', 'RW', 'RWA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (642, '642', 'РУМЫНИЯ', 'Румыния', 'RO', 'ROU')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (882, '882', 'САМОА', 'Независимое Государство Самоа', 'WS', 'WSM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (674, '674', 'САН-МАРИНО', 'Республика Сан-Марино', 'SM', 'SMR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (678, '678', 'САН-ТОМЕ И ПРИНСИПИ', 'Демократическая Республика Сан-Томе и Принсипи', 'ST', 'STP')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (682, '682', 'САУДОВСКАЯ АРАВИЯ', 'Королевство Саудовская Аравия', 'SA', 'SAU')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (748, '748', 'СВАЗИЛЕНД', 'Королевство Свазиленд', 'SZ', 'SWZ')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (654, '654', 'СВЯТАЯ ЕЛЕНА, ОСТРОВ ВОЗНЕСЕНИЯ, ТРИСТАН-ДА-КУНЬЯ', 'Святая Елена, Остров Вознесения, Тристан-Да-Кунья', 'SH', 'SHN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (580, '580', 'СЕВЕРНЫЕ МАРИАНСКИЕ ОСТРОВА', 'Содружество Северных Марианских островов', 'MP', 'MNP')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (690, '690', 'СЕЙШЕЛЫ', 'Республика Сейшелы', 'SC', 'SYC')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (652, '652', 'СЕН-БАРТЕЛЕМИ', 'Сен-Бартелеми', 'BL', 'BLM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (663, '663', 'СЕН-МАРТЕН', 'Сен-Мартен', 'MF', 'MAF')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (534, '534', 'СЕН-МАРТЕН (нидерландская часть)', 'Сен-Мартен (Нидерландская Часть)', 'SX', 'SXM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (686, '686', 'СЕНЕГАЛ', 'Республика Сенегал', 'SN', 'SEN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (670, '670', 'СЕНТ-ВИНСЕНТ И ГРЕНАДИНЫ', 'Сент-Винсент И Гренадины', 'VC', 'VCT')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (659, '659', 'СЕНТ-КИТС И НЕВИС', 'Сент-Китс И Невис', 'KN', 'KNA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (662, '662', 'СЕНТ-ЛЮСИЯ', 'Сент-Люсия', 'LC', 'LCA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (666, '666', 'СЕН-ПЬЕР И МИКЕЛОН', 'Сен-Пьер И Микелон', 'PM', 'SPM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (688, '688', 'СЕРБИЯ', 'Республика Сербия', 'RS', 'SRB')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (702, '702', 'СИНГАПУР', 'Республика Сингапур', 'SG', 'SGP')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (760, '760', 'СИРИЙСКАЯ АРАБСКАЯ РЕСПУБЛИКА', 'Сирийская Арабская Республика', 'SY', 'SYR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (703, '703', 'СЛОВАКИЯ', 'Словацкая Республика', 'SK', 'SVK')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (705, '705', 'СЛОВЕНИЯ', 'Республика Словения', 'SI', 'SVN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (826, '826', 'СОЕДИНЕННОЕ КОРОЛЕВСТВО', 'Соединенное Королевство Великобритании и Северной Ирландии', 'GB', 'GBR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (840, '840', 'СОЕДИНЕННЫЕ ШТАТЫ', 'Соединенные Штаты Америки', 'US', 'USA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (90, '90', 'СОЛОМОНОВЫ ОСТРОВА', 'Соломоновы Острова', 'SB', 'SLB')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (706, '706', 'СОМАЛИ', 'Федеративная Республика Сомали', 'SO', 'SOM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (729, '729', 'СУДАН', 'Республика Судан', 'SD', 'SDN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (740, '740', 'СУРИНАМ', 'Республика Суринам', 'SR', 'SUR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (694, '694', 'СЬЕРРА-ЛЕОНЕ', 'Республика Сьерра-Леоне', 'SL', 'SLE')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (762, '762', 'ТАДЖИКИСТАН', 'Республика Таджикистан', 'TJ', 'TJK')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (764, '764', 'ТАИЛАНД', 'Королевство Таиланд', 'TH', 'THA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (158, '158', 'ТАЙВАНЬ (КИТАЙ)', 'Тайвань (Китай)', 'TW', 'TWN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (834, '834', 'ТАНЗАНИЯ, ОБЪЕДИНЕННАЯ РЕСПУБЛИКА', 'Объединенная Республика Танзания', 'TZ', 'TZA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (768, '768', 'ТОГО', 'Тоголезская Республика', 'TG', 'TGO')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (772, '772', 'ТОКЕЛАУ', 'Токелау', 'TK', 'TKL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (776, '776', 'ТОНГА', 'Королевство Тонга', 'TO', 'TON')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (780, '780', 'ТРИНИДАД И ТОБАГО', 'Республика Тринидад и Тобаго', 'TT', 'TTO')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (798, '798', 'ТУВАЛУ', 'Тувалу', 'TV', 'TUV')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (788, '788', 'ТУНИС', 'Тунисская Республика', 'TN', 'TUN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (795, '795', 'ТУРКМЕНИЯ', 'Туркменистан', 'TM', 'TKM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (792, '792', 'ТУРЦИЯ', 'Турецкая Республика', 'TR', 'TUR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (800, '800', 'УГАНДА', 'Республика Уганда', 'UG', 'UGA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (860, '860', 'УЗБЕКИСТАН', 'Республика Узбекистан', 'UZ', 'UZB')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (804, '804', 'УКРАИНА', 'Украина', 'UA', 'UKR')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (876, '876', 'УОЛЛИС И ФУТУНА', 'Уоллис И Футуна', 'WF', 'WLF')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (858, '858', 'УРУГВАЙ', 'Восточная Республика Уругвай', 'UY', 'URY')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (234, '234', 'ФАРЕРСКИЕ ОСТРОВА', 'Фарерские Острова', 'FO', 'FRO')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (242, '242', 'ФИДЖИ', 'Республика Фиджи', 'FJ', 'FJI')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (608, '608', 'ФИЛИППИНЫ', 'Республика Филиппины', 'PH', 'PHL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (246, '246', 'ФИНЛЯНДИЯ', 'Финляндская Республика', 'FI', 'FIN')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (238, '238', 'ФОЛКЛЕНДСКИЕ ОСТРОВА (МАЛЬВИНСКИЕ)', 'Фолклендские Острова (Мальвинские)', 'FK', 'FLK')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (250, '250', 'ФРАНЦИЯ', 'Французская Республика', 'FR', 'FRA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (254, '254', 'ФРАНЦУЗСКАЯ ГВИАНА', 'Французская Гвиана', 'GF', 'GUF')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (258, '258', 'ФРАНЦУЗСКАЯ ПОЛИНЕЗИЯ', 'Французская Полинезия', 'PF', 'PYF')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (260, '260', 'ФРАНЦУЗСКИЕ ЮЖНЫЕ ТЕРРИТОРИИ', 'Французские Южные Территории', 'TF', 'ATF')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (191, '191', 'ХОРВАТИЯ', 'Республика Хорватия', 'HR', 'HRV')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (140, '140', 'ЦЕНТРАЛЬНО-АФРИКАНСКАЯ РЕСПУБЛИКА', 'Центрально-Африканская Республика', 'CF', 'CAF')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (148, '148', 'ЧАД', 'Республика Чад', 'TD', 'TCD')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (499, '499', 'ЧЕРНОГОРИЯ', 'Черногория', 'ME', 'MNE')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (203, '203', 'ЧЕШСКАЯ РЕСПУБЛИКА', 'Чешская Республика', 'CZ', 'CZE')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (152, '152', 'ЧИЛИ', 'Республика Чили', 'CL', 'CHL')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (756, '756', 'ШВЕЙЦАРИЯ', 'Швейцарская Конфедерация', 'CH', 'CHE')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (752, '752', 'ШВЕЦИЯ', 'Королевство Швеция', 'SE', 'SWE')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (744, '744', 'ШПИЦБЕРГЕН И ЯН МАЙЕН', 'Шпицберген И Ян Майен', 'SJ', 'SJM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (144, '144', 'ШРИ-ЛАНКА', 'Демократическая Социалистическая Республика Шри-Ланка', 'LK', 'LKA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (218, '218', 'ЭКВАДОР', 'Республика Эквадор', 'EC', 'ECU')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (226, '226', 'ЭКВАТОРИАЛЬНАЯ ГВИНЕЯ', 'Республика Экваториальная Гвинея', 'GQ', 'GNQ')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (248, '248', 'ЭЛАНДСКИЕ ОСТРОВА', 'Эландские Острова', 'AX', 'ALA')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (222, '222', 'ЭЛЬ-САЛЬВАДОР', 'Республика Эль-Сальвадор', 'SV', 'SLV')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (232, '232', 'ЭРИТРЕЯ', 'Эритрея', 'ER', 'ERI')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (233, '233', 'ЭСТОНИЯ', 'Эстонская Республика', 'EE', 'EST')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (231, '231', 'ЭФИОПИЯ', 'Федеративная Демократическая Республика Эфиопия', 'ET', 'ETH')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (710, '710', 'ЮЖНАЯ АФРИКА', 'Южно-Африканская Республика', 'ZA', 'ZAF')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (239, '239', 'ЮЖНАЯ ДЖОРДЖИЯ И ЮЖНЫЕ САНДВИЧЕВЫ ОСТРОВА', 'Южная Джорджия И Южные Сандвичевы Острова', 'GS', 'SGS')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (896, '896', 'ЮЖНАЯ ОСЕТИЯ', 'Республика Южная Осетия', 'OS', 'OST')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (728, '728', 'ЮЖНЫЙ СУДАН', 'Республика Южный Судан', 'SS', 'SSD')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (388, '388', 'ЯМАЙКА', 'Ямайка', 'JM', 'JAM')
INSERT INTO [RestChild].[dbo].[Country] (Id, Code, Name, FullName, SymbolCode2, SymbolCode3) VALUES (392, '392', 'ЯПОНИЯ', 'Япония', 'JP', 'JPN')
