use RestChild;

DELETE CounselorSkill
DELETE dbo.SkillVocabulary
DELETE dbo.Skill
DELETE dbo.SkillsGroup

DBCC CHECKIDENT (SkillsGroup, RESEED, 0)
DBCC CHECKIDENT (Skill, RESEED, 0)

DECLARE @LastInsert bigint;
declare @i int;

INSERT INTO dbo.SkillsGroup (Name, SortOrder, IsActive) VALUES('Художественные навыки', 100, 'true')
INSERT INTO dbo.SkillsGroup (Name, SortOrder, IsActive) VALUES('Спортивные навыки', 200, 'true')
INSERT INTO dbo.SkillsGroup (Name, SortOrder, IsActive) VALUES('Спортивный разряд', 300, 'true')
INSERT INTO dbo.SkillsGroup (Name, SortOrder, IsActive) VALUES('Иностранные языки', 400, 'true')
INSERT INTO dbo.SkillsGroup (Name, SortOrder, IsActive) VALUES('Научные знания', 500, 'true')
INSERT INTO dbo.SkillsGroup (Name, SortOrder, IsActive) VALUES('Компьютерные программы', 600, 'true')
INSERT INTO dbo.SkillsGroup (Name, SortOrder, IsActive) VALUES('Музыкальные инструменты', 700, 'true')



--Художественные навыки--
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('DJ', '100', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Аквагрим', '200', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Актерское мастерство ', '300', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Анимация и мультипликация', '400', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Бальные танцы', '500', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Батик', '600', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Бисероплетение', '700', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Брейк данс', '800', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Бумагопластика', '900', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Видео монтаж', '1000', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Видеомонтаж', '1100', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Видеооператор', '1200', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Вышивание', '1300', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Вязание', '1400', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Гобелен', '1500', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Графический дизайн', '1600', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Граффити', '1700', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Грим-визаж', '1800', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Декор', '1900', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Дизайн одежды', '2000', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Живопись', '2100', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Звукооператор', '2200', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Звукорежиссер', '2300', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Исторические танцы', '2400', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Каллиграфия', '2500', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Квиллинг', '2600', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('КВН', '2700', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Керамика', '2800', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Ковроткачество', '2900', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Компьютерный и web-дизайн дизайн', '3000', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Корнепластика', '3100', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Кружевоплетение', '3200', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Лаковая миниатюра', '3300', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Макетирование', '3400', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Макраме', '3500', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Мозаика', '3600', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Набойка', '3700', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Настольный теннис', '3800', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Оригами', '3900', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Пирография', '4000', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Пластика', '4100', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Проза (сценарии)', '4200', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Работа со звуковым оборудованием', '4300', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Работа со световым оборудованием', '4400', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Работа со стеклом', '4500', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Режиссура', '4600', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Рукоделие', '4700', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Русские народные танцы', '4800', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Скрапбукинг', '4900', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Стихосложение', '5000', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Танцы восточные', '5100', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Театральное мастерство', '5200', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Театральный кружок', '5300', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Флористика', '5400', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Фокусы', '5500', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Фотограф', '5600', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Хореография', '5700', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Хоровое пение', '5800', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Художественная обработка кожи', '5900', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Художественная обработка металла', '6000', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Художественная резьба', '6100', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Художественная роспись (металл, дерево, керамика)', '6200', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Художественное рисование', '6300', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Цирковое училище', '6400', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Чирлидинг', '6500', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Шитьё игрушек', '6600', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Эстрадно-хореографические танцы', '6700', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Эстрадный вокал', '6800', 'true', 'false', 'false', 1)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Ювелирное искусство', '6900', 'true', 'false', 'false', 1)


--Спортивные навыки--
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Аэробика', 0100, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Лыжи', 0200, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Сноуборд', 0300, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Фехтование', 0400, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Аквааэробика', 0500, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Акробатика', 0600, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Альпинизм', 0700, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Аэробика', 0800, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Баскетбол', 0900, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Бокс', 1000, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Большой теннис', 1100, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Борьба', 1200, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Велоспорт', 1300, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Водное поло', 1400, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Волейбол', 1500, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Вольная борьба', 1600, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Воркаут', 1700, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Гимнастика', 1800, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Дартс', 1900, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Дзюдо', 2000, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Йога', 2100, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Карате', 2200, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Конный спорт и верховая езда', 2300, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Легкая атлетика', 2400, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Лыжные гонки', 2500, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Мини-футбол', 2600, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Одиночное или синхронное плавание', 2700, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Пауэрлифтинг', 2800, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Петанк (Боча)', 2900, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Пилатес', 3000, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Пионербол', 3100, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('САМБО', 3200, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Слайд – аэробика', 3300, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Спортивная акробатика', 3400, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Спортивно-бальные танцы', 3500, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Степ-аэробика', 3600, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Стрельба', 3700, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Тай-бо', 3800, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Тайский бокс', 3900, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Танцевальная аэробика', 4000, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Тяжелая атлетика', 4100, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Фигурное катание', 4200, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Футбол', 4300, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Хоккей', 4400, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Художественная гимнастика', 4500, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Шахматы', 4600, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Шашки', 4700, 'true', 'false', 'false', 2)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Шейпинг', 4800, 'true', 'false', 'false', 2)


-- Спортивный разряд --
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('I Юношеский', 100, 'true', 'false', 'false', 3)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('II Юношеский', 200, 'true', 'false', 'false', 3)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('III Юношеский', 300, 'true', 'false', 'false', 3)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('I Взрослый', 400, 'true', 'false', 'false', 3)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('II Взрослый', 500, 'true', 'false', 'false', 3)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('III Взрослый', 600, 'true', 'false', 'false', 3)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('IV Взрослый', 700, 'true', 'false', 'false', 3)

-- Знаниние иностранных языков --
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Английский язык', 0100, 'true', 'false', 'true', 4)
SET @LastInsert = @@IDENTITY
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Немецкий язык', 0200, 'true', 'false', 'true', 4)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Корейский язык', 0300, 'true', 'false', 'true', 4)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Французский язык', 0400, 'true', 'false', 'true', 4)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Итальянский язык', 0500, 'true', 'false', 'true', 4)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Татарский язык', 0600, 'true', 'false', 'true', 4)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Украинский язык', 0700, 'true', 'false', 'true', 4)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Испанский язык', 0800, 'true', 'false', 'true', 4)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Сербский язык', 0900, 'true', 'false', 'true', 4)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Шведский язык', 1000, 'true', 'false', 'true', 4)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Другой', 1100, 'true', 'true', 'true', 4)

SET @i = 0;
WHILE(@i < 11)
BEGIN

	INSERT INTO dbo.SkillVocabulary(Name, IsActive, SkillId, SortOrder) VALUES ('Читаю и перевожу со словарем', 'true', @LastInsert+@i, 100)
	INSERT INTO dbo.SkillVocabulary(Name, IsActive, SkillId, SortOrder) VALUES ('Читаю и могу объяснить', 'true', @LastInsert+@i, 200)
	INSERT INTO dbo.SkillVocabulary(Name, IsActive, SkillId, SortOrder) VALUES ('Владею свободно', 'true', @LastInsert+@i, 300)

SET @i = @i + 1
END

-- Научные знания --
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Химия', 0100, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Физика', 0200, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Биология', 0300, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Астрономия', 0400, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('География', 0500, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Геология', 0600, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Культурология', 0700, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Филология', 0800, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Философия', 0900, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Антропология', 1000, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Социология', 1100, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Политология', 1200, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Педагогика', 1300, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Психология', 1400, 'true', 'false', 'false', 5)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('История России и мира', 1500, 'true', 'false', 'false', 5)

-- Компьютерные программы --
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('iMovie', 0100, 'true', 'false', 'false', 6)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('CorelDraw', 0200, 'true', 'false', 'false', 6)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Adobe Photoshop', 0300, 'true', 'false', 'false', 6)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('InDesign', 0400, 'true', 'false', 'false', 6)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('InkScape', 0500, 'true', 'false', 'false', 6)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('LightRoom', 0600, 'true', 'false', 'false', 6)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('AdobePremiere', 0700, 'true', 'false', 'false', 6)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('3D Max', 0800, 'true', 'false', 'false', 6)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('AdobeAudition', 0900, 'true', 'false', 'false', 6)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Auto Cad', 1000, 'true', 'false', 'false', 6)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('MS Office', 1100, 'true', 'false', 'false', 6)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('PinacleStudio', 1200, 'true', 'false', 'false', 6)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Sony Vegas', 1300, 'true', 'false', 'false', 6)

-- Музыкальные инструменты --
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Аккардион', 0100, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Альт', 0200, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Балалайка', 0300, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Барабаны', 0400, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Баритон', 0500, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Бас гитара', 0600, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Бубен', 0700, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Виолончель', 0800, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Гитара', 0900, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Губная гармошка', 1000, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Гусли', 1100, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Домра', 1200, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Пение ', 1300, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Пианино', 1400, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Саксафон', 1500, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Синтезатор', 1600, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Скрипка', 1700, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Трамбон', 1800, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Укулеле', 1900, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Флейта', 2000, 'true', 'false', 'false', 7)
INSERT INTO dbo.Skill(Name, SortOrder, IsActive, NeedText, NeedVocabulary, SkillsGroupId) VALUES ('Фортепиано', 2100, 'true', 'false', 'false', 7)
