SET IDENTITY_INSERT [dbo].[StateDistrict] ON

insert into dbo.StateDistrict (Id, Name, IsActive) Values(1, 'Республика Адыгея', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(4, 'Республика Алтай', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(2, 'Республика Башкортостан', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(3, 'Республика Бурятия', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(5, 'Республика Дагестан', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(6, 'Республика Ингушетия', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(7, 'Кабардино-Балкарская республика', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(8, 'Республика Калмыкия', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(9, 'Карачаево-Черкесская республика', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(10, 'Республика Карелия', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(11, 'Республика Коми', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(91, 'Республика Крым', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(12, 'Республика Марий Эл', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(13, 'Республика Мордовия', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(14, 'Республика Саха (Якутия)', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(15, 'Республика Северная Осетия — Алания', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(16, 'Республика Татарстан', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(17, 'Республика Тыва', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(18, 'Удмуртская республика', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(19, 'Республика Хакасия', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(20, 'Чеченская республика', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(21, 'Чувашская республика', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(22, 'Алтайский край', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(75, 'Забайкальский край', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(41, 'Камчатский край', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(23, 'Краснодарский край', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(24, 'Красноярский край', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(59, 'Пермский край', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(25, 'Приморский край', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(26, 'Ставропольский край', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(27, 'Хабаровский край', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(28, 'Амурская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(29, 'Архангельская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(30, 'Астраханская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(31, 'Белгородская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(32, 'Брянская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(33, 'Владимирская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(34, 'Волгоградская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(35, 'Вологодская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(36, 'Воронежская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(37, 'Ивановская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(38, 'Иркутская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(39, 'Калининградская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(40, 'Калужская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(42, 'Кемеровская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(43, 'Кировская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(44, 'Костромская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(45, 'Курганская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(46, 'Курская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(47, 'Ленинградская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(48, 'Липецкая область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(49, 'Магаданская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(50, 'Московская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(51, 'Мурманская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(52, 'Нижегородская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(53, 'Новгородская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(54, 'Новосибирская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(55, 'Омская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(56, 'Оренбургская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(57, 'Орловская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(58, 'Пензенская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(60, 'Псковская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(61, 'Ростовская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(62, 'Рязанская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(63, 'Самарская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(64, 'Саратовская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(65, 'Сахалинская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(66, 'Свердловская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(67, 'Смоленская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(68, 'Тамбовская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(69, 'Тверская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(70, 'Томская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(71, 'Тульская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(72, 'Тюменская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(73, 'Ульяновская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(74, 'Челябинская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(76, 'Ярославская область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(77, 'Москва', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(78, 'Санкт-Петербург', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(92, 'Севастополь', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(79, 'Еврейская автономная область', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(83, 'Ненецкий автономный округ', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(86, 'Ханты-Мансийский автономный округ - Югра', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(87, 'Чукотский автономный округ', 1)
insert into dbo.StateDistrict (Id, Name, IsActive) Values(89, 'Ямало-Ненецкий автономный округ', 1)


SET IDENTITY_INSERT [dbo].[StateDistrict] OFF