//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestChild.ERL.ERLService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1")]
    public partial class citizen_benefitcategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string benefitcategory_pkField;
        
        private System.DateTime begin_dateField;
        
        private System.DateTime end_dateField;
        
        private bool end_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string benefitcategory_pk {
            get {
                return this.benefitcategory_pkField;
            }
            set {
                this.benefitcategory_pkField = value;
                this.RaisePropertyChanged("benefitcategory_pk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime begin_date {
            get {
                return this.begin_dateField;
            }
            set {
                this.begin_dateField = value;
                this.RaisePropertyChanged("begin_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime end_date {
            get {
                return this.end_dateField;
            }
            set {
                this.end_dateField = value;
                this.RaisePropertyChanged("end_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool end_dateSpecified {
            get {
                return this.end_dateFieldSpecified;
            }
            set {
                this.end_dateFieldSpecified = value;
                this.RaisePropertyChanged("end_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1")]
    public partial class address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bti_identityField;
        
        private string post_indexField;
        
        private string settlement_codeField;
        
        private string street_codeField;
        
        private string street_nameField;
        
        private string house_codeField;
        
        private string houseField;
        
        private string corpusField;
        
        private string buildingField;
        
        private string flatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bti_identity {
            get {
                return this.bti_identityField;
            }
            set {
                this.bti_identityField = value;
                this.RaisePropertyChanged("bti_identity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string post_index {
            get {
                return this.post_indexField;
            }
            set {
                this.post_indexField = value;
                this.RaisePropertyChanged("post_index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string settlement_code {
            get {
                return this.settlement_codeField;
            }
            set {
                this.settlement_codeField = value;
                this.RaisePropertyChanged("settlement_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string street_code {
            get {
                return this.street_codeField;
            }
            set {
                this.street_codeField = value;
                this.RaisePropertyChanged("street_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string street_name {
            get {
                return this.street_nameField;
            }
            set {
                this.street_nameField = value;
                this.RaisePropertyChanged("street_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string house_code {
            get {
                return this.house_codeField;
            }
            set {
                this.house_codeField = value;
                this.RaisePropertyChanged("house_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string house {
            get {
                return this.houseField;
            }
            set {
                this.houseField = value;
                this.RaisePropertyChanged("house");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string corpus {
            get {
                return this.corpusField;
            }
            set {
                this.corpusField = value;
                this.RaisePropertyChanged("corpus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
                this.RaisePropertyChanged("building");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string flat {
            get {
                return this.flatField;
            }
            set {
                this.flatField = value;
                this.RaisePropertyChanged("flat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1")]
    public partial class citizen_address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int address_typeField;
        
        private address addressField;
        
        private string address_textField;
        
        private System.DateTime registration_dateField;
        
        private bool registration_dateFieldSpecified;
        
        private System.DateTime actualize_dateField;
        
        private bool actualize_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int address_type {
            get {
                return this.address_typeField;
            }
            set {
                this.address_typeField = value;
                this.RaisePropertyChanged("address_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public address address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string address_text {
            get {
                return this.address_textField;
            }
            set {
                this.address_textField = value;
                this.RaisePropertyChanged("address_text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime registration_date {
            get {
                return this.registration_dateField;
            }
            set {
                this.registration_dateField = value;
                this.RaisePropertyChanged("registration_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool registration_dateSpecified {
            get {
                return this.registration_dateFieldSpecified;
            }
            set {
                this.registration_dateFieldSpecified = value;
                this.RaisePropertyChanged("registration_dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="date")]
        public System.DateTime actualize_date {
            get {
                return this.actualize_dateField;
            }
            set {
                this.actualize_dateField = value;
                this.RaisePropertyChanged("actualize_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actualize_dateSpecified {
            get {
                return this.actualize_dateFieldSpecified;
            }
            set {
                this.actualize_dateFieldSpecified = value;
                this.RaisePropertyChanged("actualize_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1")]
    public partial class CitizenPrivilegeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdField;
        
        private string citizen_pkField;
        
        private citizen_address[] citizen_addressesField;
        
        private citizen_benefitcategory[] citizen_benefitcategoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string citizen_pk {
            get {
                return this.citizen_pkField;
            }
            set {
                this.citizen_pkField = value;
                this.RaisePropertyChanged("citizen_pk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public citizen_address[] citizen_addresses {
            get {
                return this.citizen_addressesField;
            }
            set {
                this.citizen_addressesField = value;
                this.RaisePropertyChanged("citizen_addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public citizen_benefitcategory[] citizen_benefitcategories {
            get {
                return this.citizen_benefitcategoriesField;
            }
            set {
                this.citizen_benefitcategoriesField = value;
                this.RaisePropertyChanged("citizen_benefitcategories");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1")]
    public partial class RequestIdentityDocument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string doctype_pkField;
        
        private string serialField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string doctype_pk {
            get {
                return this.doctype_pkField;
            }
            set {
                this.doctype_pkField = value;
                this.RaisePropertyChanged("doctype_pk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1")]
    public partial class Name : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string surnameField;
        
        private string firstnameField;
        
        private string patronymicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
                this.RaisePropertyChanged("firstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string patronymic {
            get {
                return this.patronymicField;
            }
            set {
                this.patronymicField = value;
                this.RaisePropertyChanged("patronymic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1")]
    public partial class RequestPerson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Name nameField;
        
        private System.DateTime birthdayField;
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Name name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("birthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identity_document", typeof(RequestIdentityDocument), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("oms", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("snils", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":identity_document")]
        identity_document,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":oms")]
        oms,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":snils")]
        snils,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1")]
    public partial class CitizenPrivilegeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdField;
        
        private object itemField;
        
        private string item1Field;
        
        private Item1ChoiceType item1ElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citizen", typeof(RequestPerson), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("citizen_pk", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("benefitcategory_pk", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("benefittype_pk", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item1ElementName")]
        public string Item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
                this.RaisePropertyChanged("Item1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Item1ChoiceType Item1ElementName {
            get {
                return this.item1ElementNameField;
            }
            set {
                this.item1ElementNameField = value;
                this.RaisePropertyChanged("Item1ElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1", IncludeInSchema=false)]
    public enum Item1ChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":benefitcategory_pk")]
        benefitcategory_pk,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":benefittype_pk")]
        benefittype_pk,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1")]
    public partial class GetPrivilegeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string senderField;
        
        private CitizenPrivilegeRequest[] citizenRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citizenRequest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CitizenPrivilegeRequest[] citizenRequest {
            get {
                return this.citizenRequestField;
            }
            set {
                this.citizenRequestField = value;
                this.RaisePropertyChanged("citizenRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1", ConfigurationName="ERLService.OivPrivilegeServicePortType")]
    public interface OivPrivilegeServicePortType {
        
        // CODEGEN: Generating message contract since the operation getPrivilege is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getPrivilege", ReplyAction="http://erl.msr.com/schemas/privilege/oiv/v1/OivPrivilegeServicePortType/getPrivil" +
            "egeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RestChild.ERL.ERLService.ServiceException), Action="http://erl.msr.com/schemas/privilege/oiv/v1/OivPrivilegeServicePortType/getPrivil" +
            "ege/Fault/ServiceException", Name="simpleFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citizen_address[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citizen_benefitcategory[]))]
        RestChild.ERL.ERLService.getPrivilegeResponse getPrivilege(RestChild.ERL.ERLService.getPrivilegeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getPrivilege", ReplyAction="http://erl.msr.com/schemas/privilege/oiv/v1/OivPrivilegeServicePortType/getPrivil" +
            "egeResponse")]
        System.Threading.Tasks.Task<RestChild.ERL.ERLService.getPrivilegeResponse> getPrivilegeAsync(RestChild.ERL.ERLService.getPrivilegeRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPrivilegeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://erl.msr.com/schemas/privilege/oiv/v1", Order=0)]
        public RestChild.ERL.ERLService.GetPrivilegeRequest getPrivilegeRequest;
        
        public getPrivilegeRequest1() {
        }
        
        public getPrivilegeRequest1(RestChild.ERL.ERLService.GetPrivilegeRequest getPrivilegeRequest) {
            this.getPrivilegeRequest = getPrivilegeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPrivilegeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPrivilegeResponse", Namespace="http://erl.msr.com/schemas/privilege/oiv/v1", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("citizenResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RestChild.ERL.ERLService.CitizenPrivilegeResponse[] getPrivilegeResponse1;
        
        public getPrivilegeResponse() {
        }
        
        public getPrivilegeResponse(RestChild.ERL.ERLService.CitizenPrivilegeResponse[] getPrivilegeResponse1) {
            this.getPrivilegeResponse1 = getPrivilegeResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OivPrivilegeServicePortTypeChannel : RestChild.ERL.ERLService.OivPrivilegeServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OivPrivilegeServicePortTypeClient : System.ServiceModel.ClientBase<RestChild.ERL.ERLService.OivPrivilegeServicePortType>, RestChild.ERL.ERLService.OivPrivilegeServicePortType {
        
        public OivPrivilegeServicePortTypeClient() {
        }
        
        public OivPrivilegeServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OivPrivilegeServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OivPrivilegeServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OivPrivilegeServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RestChild.ERL.ERLService.getPrivilegeResponse RestChild.ERL.ERLService.OivPrivilegeServicePortType.getPrivilege(RestChild.ERL.ERLService.getPrivilegeRequest1 request) {
            return base.Channel.getPrivilege(request);
        }
        
        public RestChild.ERL.ERLService.CitizenPrivilegeResponse[] getPrivilege(RestChild.ERL.ERLService.GetPrivilegeRequest getPrivilegeRequest) {
            RestChild.ERL.ERLService.getPrivilegeRequest1 inValue = new RestChild.ERL.ERLService.getPrivilegeRequest1();
            inValue.getPrivilegeRequest = getPrivilegeRequest;
            RestChild.ERL.ERLService.getPrivilegeResponse retVal = ((RestChild.ERL.ERLService.OivPrivilegeServicePortType)(this)).getPrivilege(inValue);
            return retVal.getPrivilegeResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RestChild.ERL.ERLService.getPrivilegeResponse> RestChild.ERL.ERLService.OivPrivilegeServicePortType.getPrivilegeAsync(RestChild.ERL.ERLService.getPrivilegeRequest1 request) {
            return base.Channel.getPrivilegeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RestChild.ERL.ERLService.getPrivilegeResponse> getPrivilegeAsync(RestChild.ERL.ERLService.GetPrivilegeRequest getPrivilegeRequest) {
            RestChild.ERL.ERLService.getPrivilegeRequest1 inValue = new RestChild.ERL.ERLService.getPrivilegeRequest1();
            inValue.getPrivilegeRequest = getPrivilegeRequest;
            return ((RestChild.ERL.ERLService.OivPrivilegeServicePortType)(this)).getPrivilegeAsync(inValue);
        }
    }
}
