//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

//
// This source code was auto-generated by xsd, Version=4.7.3081.0.
//
namespace RestChild.Comon.Exchange.Zagz
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4",
        IsNullable = false)]
    public partial class informResponse
    {

        private informResponseСведРегРожд сведРегРождField;

        private informResponseСведРегЗаклБрак[] сведРегЗаклБракField;

        private informResponseСведРегРстржБрак[] сведРегРстржБракField;

        private informResponseСвеРегОтцов[] свеРегОтцовField;

        private informResponseСведРегПерИмя[] сведРегПерИмяField;

        private informResponseСведРегСмерт сведРегСмертField;

        private string идЗапросField;

        private informResponseТипЗапрос типЗапросField;

        private informResponseТипАГСЗапрос типАГСЗапросField;

        private string номерЗаписЗапросField;

        private System.DateTime датаСведField;

        private informResponseРезОбраб резОбрабField;

        private informResponseКодСтатус кодСтатусField;

        private bool кодСтатусFieldSpecified;

        /// <remarks/>
        public informResponseСведРегРожд СведРегРожд
        {
            get { return this.сведРегРождField; }
            set { this.сведРегРождField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведРегЗаклБрак")]
        public informResponseСведРегЗаклБрак[] СведРегЗаклБрак
        {
            get { return this.сведРегЗаклБракField; }
            set { this.сведРегЗаклБракField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведРегРстржБрак")]
        public informResponseСведРегРстржБрак[] СведРегРстржБрак
        {
            get { return this.сведРегРстржБракField; }
            set { this.сведРегРстржБракField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвеРегОтцов")]
        public informResponseСвеРегОтцов[] СвеРегОтцов
        {
            get { return this.свеРегОтцовField; }
            set { this.свеРегОтцовField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведРегПерИмя")]
        public informResponseСведРегПерИмя[] СведРегПерИмя
        {
            get { return this.сведРегПерИмяField; }
            set { this.сведРегПерИмяField = value; }
        }

        /// <remarks/>
        public informResponseСведРегСмерт СведРегСмерт
        {
            get { return this.сведРегСмертField; }
            set { this.сведРегСмертField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдЗапрос
        {
            get { return this.идЗапросField; }
            set { this.идЗапросField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public informResponseТипЗапрос ТипЗапрос
        {
            get { return this.типЗапросField; }
            set { this.типЗапросField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public informResponseТипАГСЗапрос ТипАГСЗапрос
        {
            get { return this.типАГСЗапросField; }
            set { this.типАГСЗапросField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерЗаписЗапрос
        {
            get { return this.номерЗаписЗапросField; }
            set { this.номерЗаписЗапросField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаСвед
        {
            get { return this.датаСведField; }
            set { this.датаСведField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public informResponseРезОбраб РезОбраб
        {
            get { return this.резОбрабField; }
            set { this.резОбрабField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public informResponseКодСтатус КодСтатус
        {
            get { return this.кодСтатусField; }
            set { this.кодСтатусField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КодСтатусSpecified
        {
            get { return this.кодСтатусFieldSpecified; }
            set { this.кодСтатусFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегРожд
    {

        private ОрганЗАГСТип органЗАГСField;

        private СтатусЗаписиТип статусЗаписиField;

        private СведСвидетТип[] свидетРождField;

        private informResponseСведРегРождПрдСведРег прдСведРегField;

        private string номерЗаписField;

        private System.DateTime датаЗаписField;

        /// <remarks/>
        public ОрганЗАГСТип ОрганЗАГС
        {
            get { return this.органЗАГСField; }
            set { this.органЗАГСField = value; }
        }

        /// <remarks/>
        public СтатусЗаписиТип СтатусЗаписи
        {
            get { return this.статусЗаписиField; }
            set { this.статусЗаписиField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвидетРожд")]
        public СведСвидетТип[] СвидетРожд
        {
            get { return this.свидетРождField; }
            set { this.свидетРождField = value; }
        }

        /// <remarks/>
        public informResponseСведРегРождПрдСведРег ПрдСведРег
        {
            get { return this.прдСведРегField; }
            set { this.прдСведРегField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерЗапис
        {
            get { return this.номерЗаписField; }
            set { this.номерЗаписField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаЗапис
        {
            get { return this.датаЗаписField; }
            set { this.датаЗаписField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class ОрганЗАГСТип
    {

        private string наимЗАГСField;

        private string кодЗАГСField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЗАГС
        {
            get { return this.наимЗАГСField; }
            set { this.наимЗАГСField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодЗАГС
        {
            get { return this.кодЗАГСField; }
            set { this.кодЗАГСField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class СупругТип
    {

        private object itemField;

        private object item1Field;

        private object item2Field;

        private object item3Field;

        private object item4Field;

        private Item4ChoiceType item4ElementNameField;

        private МестоТип местоРожденField;

        private object item5Field;

        private УдЛичнФЛТип удЛичнФЛField;

        private object item6Field;

        private string оКСМField;

        private string наимСтраныField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрФамилияДо", typeof(СупругТипПрФамилияДо))]
        [System.Xml.Serialization.XmlElementAttribute("ФамилияДо", typeof(string))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрФамилияПосле", typeof(СупругТипПрФамилияПосле))]
        [System.Xml.Serialization.XmlElementAttribute("ФамилияПосле", typeof(string))]
        public object Item1
        {
            get { return this.item1Field; }
            set { this.item1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Имя", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрИмя", typeof(СупругТипПрИмя))]
        public object Item2
        {
            get { return this.item2Field; }
            set { this.item2Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Отчество", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрОтчество", typeof(СупругТипПрОтчество))]
        public object Item3
        {
            get { return this.item3Field; }
            set { this.item3Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГодРожд", typeof(string), DataType = "gYear")]
        [System.Xml.Serialization.XmlElementAttribute("ДатаРожд", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("МесГодРожд", typeof(string), DataType = "gYearMonth")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item4ElementName")]
        public object Item4
        {
            get { return this.item4Field; }
            set { this.item4Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Item4ChoiceType Item4ElementName
        {
            get { return this.item4ElementNameField; }
            set { this.item4ElementNameField = value; }
        }

        /// <remarks/>
        public МестоТип МестоРожден
        {
            get { return this.местоРожденField; }
            set { this.местоРожденField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрМЖИн", typeof(АдрМЖИнТип))]
        [System.Xml.Serialization.XmlElementAttribute("АдрМЖРФ", typeof(АдрМЖРФТип))]
        public object Item5
        {
            get { return this.item5Field; }
            set { this.item5Field = value; }
        }

        /// <remarks/>
        public УдЛичнФЛТип УдЛичнФЛ
        {
            get { return this.удЛичнФЛField; }
            set { this.удЛичнФЛField = value; }
        }

        /// <remarks/>
        public object Item6
        {
            get { return this.item6Field; }
            set { this.item6Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКСМ
        {
            get { return this.оКСМField; }
            set { this.оКСМField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимСтраны
        {
            get { return this.наимСтраныField; }
            set { this.наимСтраныField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public enum СупругТипПрФамилияДо
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public enum СупругТипПрФамилияПосле
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public enum СупругТипПрИмя
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public enum СупругТипПрОтчество
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4",
        IncludeInSchema = false)]
    public enum Item4ChoiceType
    {

        /// <remarks/>
        ГодРожд,

        /// <remarks/>
        ДатаРожд,

        /// <remarks/>
        МесГодРожд,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class МестоТип
    {

        private string местоТекстField;

        private string кодСтраныField;

        private string наимСтраныField;

        private string регионField;

        private string наимСубъектField;

        private string районField;

        private string городField;

        private string населПунктField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string МестоТекст
        {
            get { return this.местоТекстField; }
            set { this.местоТекстField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодСтраны
        {
            get { return this.кодСтраныField; }
            set { this.кодСтраныField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимСтраны
        {
            get { return this.наимСтраныField; }
            set { this.наимСтраныField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Регион
        {
            get { return this.регионField; }
            set { this.регионField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимСубъект
        {
            get { return this.наимСубъектField; }
            set { this.наимСубъектField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Район
        {
            get { return this.районField; }
            set { this.районField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Город
        {
            get { return this.городField; }
            set { this.городField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаселПункт
        {
            get { return this.населПунктField; }
            set { this.населПунктField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class АдрМЖИнТип
    {

        private string оКСМField;

        private string наимСтраныField;

        private string адрТекстField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКСМ
        {
            get { return this.оКСМField; }
            set { this.оКСМField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимСтраны
        {
            get { return this.наимСтраныField; }
            set { this.наимСтраныField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АдрТекст
        {
            get { return this.адрТекстField; }
            set { this.адрТекстField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class АдрМЖРФТип
    {

        private object itemField;

        private string адрРФТекстField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрКЛАДР", typeof(АдрКЛАДРТип))]
        [System.Xml.Serialization.XmlElementAttribute("АдрФИАС", typeof(АдрФИАСТип))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АдрРФТекст
        {
            get { return this.адрРФТекстField; }
            set { this.адрРФТекстField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class АдрКЛАДРТип
    {

        private string индексField;

        private string кодРегионField;

        private string наимРегионField;

        private string районField;

        private string городField;

        private string населПунктField;

        private string улицаField;

        private string домField;

        private string корпусField;

        private string квартField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Индекс
        {
            get { return this.индексField; }
            set { this.индексField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодРегион
        {
            get { return this.кодРегионField; }
            set { this.кодРегионField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимРегион
        {
            get { return this.наимРегионField; }
            set { this.наимРегионField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Район
        {
            get { return this.районField; }
            set { this.районField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Город
        {
            get { return this.городField; }
            set { this.городField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаселПункт
        {
            get { return this.населПунктField; }
            set { this.населПунктField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Улица
        {
            get { return this.улицаField; }
            set { this.улицаField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Дом
        {
            get { return this.домField; }
            set { this.домField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Корпус
        {
            get { return this.корпусField; }
            set { this.корпусField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Кварт
        {
            get { return this.квартField; }
            set { this.квартField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class АдрФИАСТип
    {

        private string регионField;

        private ВидНаимКодТип муниципРайонField;

        private ВидНаимКодТип городСелПоселенField;

        private ВидНаимТип населенПунктField;

        private ТипНаимТип элПланСтруктурField;

        private ТипНаимТип элУлДорСетиField;

        private string земелУчастокField;

        private НомерТип[] зданиеField;

        private НомерТип помещЗданияField;

        private НомерТип помещКвартирыField;

        private string идНомField;

        private string индексField;

        /// <remarks/>
        public string Регион
        {
            get { return this.регионField; }
            set { this.регионField = value; }
        }

        /// <remarks/>
        public ВидНаимКодТип МуниципРайон
        {
            get { return this.муниципРайонField; }
            set { this.муниципРайонField = value; }
        }

        /// <remarks/>
        public ВидНаимКодТип ГородСелПоселен
        {
            get { return this.городСелПоселенField; }
            set { this.городСелПоселенField = value; }
        }

        /// <remarks/>
        public ВидНаимТип НаселенПункт
        {
            get { return this.населенПунктField; }
            set { this.населенПунктField = value; }
        }

        /// <remarks/>
        public ТипНаимТип ЭлПланСтруктур
        {
            get { return this.элПланСтруктурField; }
            set { this.элПланСтруктурField = value; }
        }

        /// <remarks/>
        public ТипНаимТип ЭлУлДорСети
        {
            get { return this.элУлДорСетиField; }
            set { this.элУлДорСетиField = value; }
        }

        /// <remarks/>
        public string ЗемелУчасток
        {
            get { return this.земелУчастокField; }
            set { this.земелУчастокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Здание")]
        public НомерТип[] Здание
        {
            get { return this.зданиеField; }
            set { this.зданиеField = value; }
        }

        /// <remarks/>
        public НомерТип ПомещЗдания
        {
            get { return this.помещЗданияField; }
            set { this.помещЗданияField = value; }
        }

        /// <remarks/>
        public НомерТип ПомещКвартиры
        {
            get { return this.помещКвартирыField; }
            set { this.помещКвартирыField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдНом
        {
            get { return this.идНомField; }
            set { this.идНомField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Индекс
        {
            get { return this.индексField; }
            set { this.индексField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class ВидНаимКодТип
    {

        private string видКодField;

        private string наимField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВидКод
        {
            get { return this.видКодField; }
            set { this.видКодField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Наим
        {
            get { return this.наимField; }
            set { this.наимField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class ВидНаимТип
    {

        private string видField;

        private string наимField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Вид
        {
            get { return this.видField; }
            set { this.видField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Наим
        {
            get { return this.наимField; }
            set { this.наимField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class ТипНаимТип
    {

        private string типField;

        private string наимField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Тип
        {
            get { return this.типField; }
            set { this.типField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Наим
        {
            get { return this.наимField; }
            set { this.наимField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class НомерТип
    {

        private string типField;

        private string номерField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Тип
        {
            get { return this.типField; }
            set { this.типField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Номер
        {
            get { return this.номерField; }
            set { this.номерField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class УдЛичнФЛТип
    {

        private string кодВидДокField;

        private string наимДокField;

        private string серНомДокField;

        private System.DateTime датаДокField;

        private bool датаДокFieldSpecified;

        private string выдДокField;

        private string кодВыдДокField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодВидДок
        {
            get { return this.кодВидДокField; }
            set { this.кодВидДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДок
        {
            get { return this.наимДокField; }
            set { this.наимДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СерНомДок
        {
            get { return this.серНомДокField; }
            set { this.серНомДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаДок
        {
            get { return this.датаДокField; }
            set { this.датаДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДатаДокSpecified
        {
            get { return this.датаДокFieldSpecified; }
            set { this.датаДокFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВыдДок
        {
            get { return this.выдДокField; }
            set { this.выдДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодВыдДок
        {
            get { return this.кодВыдДокField; }
            set { this.кодВыдДокField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class СведРодитТип
    {

        private ФИОПрТип фИОField;

        private МестоТип местоРожденField;

        private object itemField;

        private ItemChoiceType1 itemElementNameField;

        private УдЛичнФЛТип удЛичнФЛField;

        private object item1Field;

        private string оКСМField;

        private string наимСтраныField;

        /// <remarks/>
        public ФИОПрТип ФИО
        {
            get { return this.фИОField; }
            set { this.фИОField = value; }
        }

        /// <remarks/>
        public МестоТип МестоРожден
        {
            get { return this.местоРожденField; }
            set { this.местоРожденField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГодРожд", typeof(string), DataType = "gYear")]
        [System.Xml.Serialization.XmlElementAttribute("ДатаРожд", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("МесГодРожд", typeof(string), DataType = "gYearMonth")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }

        /// <remarks/>
        public УдЛичнФЛТип УдЛичнФЛ
        {
            get { return this.удЛичнФЛField; }
            set { this.удЛичнФЛField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрМЖИн", typeof(АдрМЖИнТип))]
        [System.Xml.Serialization.XmlElementAttribute("АдрМЖРФ", typeof(АдрМЖРФТип))]
        public object Item1
        {
            get { return this.item1Field; }
            set { this.item1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКСМ
        {
            get { return this.оКСМField; }
            set { this.оКСМField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимСтраны
        {
            get { return this.наимСтраныField; }
            set { this.наимСтраныField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class ФИОПрТип
    {

        private object itemField;

        private object item1Field;

        private object item2Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрФамилия", typeof(ФИОПрТипПрФамилия))]
        [System.Xml.Serialization.XmlElementAttribute("Фамилия", typeof(string))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Имя", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрИмя", typeof(ФИОПрТипПрИмя))]
        public object Item1
        {
            get { return this.item1Field; }
            set { this.item1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Отчество", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрОтчество", typeof(ФИОПрТипПрОтчество))]
        public object Item2
        {
            get { return this.item2Field; }
            set { this.item2Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public enum ФИОПрТипПрФамилия
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public enum ФИОПрТипПрИмя
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public enum ФИОПрТипПрОтчество
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4",
        IncludeInSchema = false)]
    public enum ItemChoiceType1
    {

        /// <remarks/>
        ГодРожд,

        /// <remarks/>
        ДатаРожд,

        /// <remarks/>
        МесГодРожд,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class СведСвидетТип
    {

        private string серияСвидетField;

        private string номерСвидетField;

        private System.DateTime датаВыдСвидетField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СерияСвидет
        {
            get { return this.серияСвидетField; }
            set { this.серияСвидетField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерСвидет
        {
            get { return this.номерСвидетField; }
            set { this.номерСвидетField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаВыдСвидет
        {
            get { return this.датаВыдСвидетField; }
            set { this.датаВыдСвидетField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public partial class СтатусЗаписиТип
    {

        private System.DateTime датаНачСтатусField;

        private СтатусЗаписиТипКодСтатус кодСтатусField;

        private string наимСтатусField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаНачСтатус
        {
            get { return this.датаНачСтатусField; }
            set { this.датаНачСтатусField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СтатусЗаписиТипКодСтатус КодСтатус
        {
            get { return this.кодСтатусField; }
            set { this.кодСтатусField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимСтатус
        {
            get { return this.наимСтатусField; }
            set { this.наимСтатусField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/types/4.0.4")]
    public enum СтатусЗаписиТипКодСтатус
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегРождПрдСведРег
    {

        private informResponseСведРегРождПрдСведРегСведРодившемся сведРодившемсяField;

        private СведРодитТип сведМатьField;

        private СведРодитТип сведОтецField;

        private informResponseСведРегРождПрдСведРегСведДокРод сведДокРодField;

        private string колРодДетейField;

        /// <remarks/>
        public informResponseСведРегРождПрдСведРегСведРодившемся СведРодившемся
        {
            get { return this.сведРодившемсяField; }
            set { this.сведРодившемсяField = value; }
        }

        /// <remarks/>
        public СведРодитТип СведМать
        {
            get { return this.сведМатьField; }
            set { this.сведМатьField = value; }
        }

        /// <remarks/>
        public СведРодитТип СведОтец
        {
            get { return this.сведОтецField; }
            set { this.сведОтецField = value; }
        }

        /// <remarks/>
        public informResponseСведРегРождПрдСведРегСведДокРод СведДокРод
        {
            get { return this.сведДокРодField; }
            set { this.сведДокРодField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string КолРодДетей
        {
            get { return this.колРодДетейField; }
            set { this.колРодДетейField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегРождПрдСведРегСведРодившемся
    {

        private ФИОПрТип фИОРождField;

        private object itemField;

        private ItemChoiceType itemElementNameField;

        private МестоТип местоРожденField;

        private informResponseСведРегРождПрдСведРегСведРодившемсяЖивМертв живМертвField;

        private informResponseСведРегРождПрдСведРегСведРодившемсяПол полField;

        /// <remarks/>
        public ФИОПрТип ФИОРожд
        {
            get { return this.фИОРождField; }
            set { this.фИОРождField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГодРожд", typeof(string), DataType = "gYear")]
        [System.Xml.Serialization.XmlElementAttribute("ДатаРожд", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("МесГодРожд", typeof(string), DataType = "gYearMonth")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }

        /// <remarks/>
        public МестоТип МестоРожден
        {
            get { return this.местоРожденField; }
            set { this.местоРожденField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public informResponseСведРегРождПрдСведРегСведРодившемсяЖивМертв ЖивМертв
        {
            get { return this.живМертвField; }
            set { this.живМертвField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public informResponseСведРегРождПрдСведРегСведРодившемсяПол Пол
        {
            get { return this.полField; }
            set { this.полField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4",
        IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        ГодРожд,

        /// <remarks/>
        ДатаРожд,

        /// <remarks/>
        МесГодРожд,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public enum informResponseСведРегРождПрдСведРегСведРодившемсяЖивМертв
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public enum informResponseСведРегРождПрдСведРегСведРодившемсяПол
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегРождПрдСведРегСведДокРод
    {

        private object itemField;

        private ItemChoiceType2 itemElementNameField;

        private string кодДокField;

        private string наимДокField;

        private string серНомДокField;

        private System.DateTime датаДокField;

        private bool датаДокFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НаимОрг", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ФИОИП", typeof(ФИОПрТип))]
        [System.Xml.Serialization.XmlElementAttribute("ФИОФЛ", typeof(ФИОПрТип))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодДок
        {
            get { return this.кодДокField; }
            set { this.кодДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДок
        {
            get { return this.наимДокField; }
            set { this.наимДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СерНомДок
        {
            get { return this.серНомДокField; }
            set { this.серНомДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаДок
        {
            get { return this.датаДокField; }
            set { this.датаДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДатаДокSpecified
        {
            get { return this.датаДокFieldSpecified; }
            set { this.датаДокFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4",
        IncludeInSchema = false)]
    public enum ItemChoiceType2
    {

        /// <remarks/>
        НаимОрг,

        /// <remarks/>
        ФИОИП,

        /// <remarks/>
        ФИОФЛ,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегЗаклБрак
    {

        private ОрганЗАГСТип органЗАГСField;

        private СтатусЗаписиТип статусЗаписиField;

        private СведСвидетТип сведСвидетField;

        private informResponseСведРегЗаклБракПрдСведРег прдСведРегField;

        private string номерЗаписField;

        private System.DateTime датаЗаписField;

        /// <remarks/>
        public ОрганЗАГСТип ОрганЗАГС
        {
            get { return this.органЗАГСField; }
            set { this.органЗАГСField = value; }
        }

        /// <remarks/>
        public СтатусЗаписиТип СтатусЗаписи
        {
            get { return this.статусЗаписиField; }
            set { this.статусЗаписиField = value; }
        }

        /// <remarks/>
        public СведСвидетТип СведСвидет
        {
            get { return this.сведСвидетField; }
            set { this.сведСвидетField = value; }
        }

        /// <remarks/>
        public informResponseСведРегЗаклБракПрдСведРег ПрдСведРег
        {
            get { return this.прдСведРегField; }
            set { this.прдСведРегField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерЗапис
        {
            get { return this.номерЗаписField; }
            set { this.номерЗаписField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаЗапис
        {
            get { return this.датаЗаписField; }
            set { this.датаЗаписField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегЗаклБракПрдСведРег
    {

        private informResponseСведРегЗаклБракПрдСведРегСведЛицБрак сведЛицБракField;

        private informResponseСведРегЗаклБракПрдСведРегПризСвед призСведField;

        private System.DateTime датаЗаклБракField;

        /// <remarks/>
        public informResponseСведРегЗаклБракПрдСведРегСведЛицБрак СведЛицБрак
        {
            get { return this.сведЛицБракField; }
            set { this.сведЛицБракField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public informResponseСведРегЗаклБракПрдСведРегПризСвед ПризСвед
        {
            get { return this.призСведField; }
            set { this.призСведField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаЗаклБрак
        {
            get { return this.датаЗаклБракField; }
            set { this.датаЗаклБракField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегЗаклБракПрдСведРегСведЛицБрак
    {

        private СупругТип супругField;

        private СупругТип супругаField;

        /// <remarks/>
        public СупругТип Супруг
        {
            get { return this.супругField; }
            set { this.супругField = value; }
        }

        /// <remarks/>
        public СупругТип Супруга
        {
            get { return this.супругаField; }
            set { this.супругаField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public enum informResponseСведРегЗаклБракПрдСведРегПризСвед
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегРстржБрак
    {

        private ОрганЗАГСТип органЗАГСField;

        private СтатусЗаписиТип статусЗаписиField;

        private СведСвидетТип[] сведСвидетField;

        private informResponseСведРегРстржБракПрдСведРег прдСведРегField;

        private string номерЗаписField;

        private System.DateTime датаЗаписField;

        /// <remarks/>
        public ОрганЗАГСТип ОрганЗАГС
        {
            get { return this.органЗАГСField; }
            set { this.органЗАГСField = value; }
        }

        /// <remarks/>
        public СтатусЗаписиТип СтатусЗаписи
        {
            get { return this.статусЗаписиField; }
            set { this.статусЗаписиField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведСвидет")]
        public СведСвидетТип[] СведСвидет
        {
            get { return this.сведСвидетField; }
            set { this.сведСвидетField = value; }
        }

        /// <remarks/>
        public informResponseСведРегРстржБракПрдСведРег ПрдСведРег
        {
            get { return this.прдСведРегField; }
            set { this.прдСведРегField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерЗапис
        {
            get { return this.номерЗаписField; }
            set { this.номерЗаписField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаЗапис
        {
            get { return this.датаЗаписField; }
            set { this.датаЗаписField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегРстржБракПрдСведРег
    {

        private informResponseСведРегРстржБракПрдСведРегСведЛицБрак сведЛицБракField;

        private informResponseСведРегРстржБракПрдСведРегПризСвед призСведField;

        private System.DateTime датаПрекрБракField;

        /// <remarks/>
        public informResponseСведРегРстржБракПрдСведРегСведЛицБрак СведЛицБрак
        {
            get { return this.сведЛицБракField; }
            set { this.сведЛицБракField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public informResponseСведРегРстржБракПрдСведРегПризСвед ПризСвед
        {
            get { return this.призСведField; }
            set { this.призСведField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаПрекрБрак
        {
            get { return this.датаПрекрБракField; }
            set { this.датаПрекрБракField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегРстржБракПрдСведРегСведЛицБрак
    {

        private СупругТип супругField;

        private СупругТип супругаField;

        /// <remarks/>
        public СупругТип Супруг
        {
            get { return this.супругField; }
            set { this.супругField = value; }
        }

        /// <remarks/>
        public СупругТип Супруга
        {
            get { return this.супругаField; }
            set { this.супругаField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public enum informResponseСведРегРстржБракПрдСведРегПризСвед
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСвеРегОтцов
    {

        private ОрганЗАГСТип органЗАГСField;

        private СтатусЗаписиТип статусЗаписиField;

        private СведСвидетТип сведСвидетField;

        private informResponseСвеРегОтцовПрдСведРег прдСведРегField;

        private string номерЗаписField;

        private System.DateTime датаЗаписField;

        /// <remarks/>
        public ОрганЗАГСТип ОрганЗАГС
        {
            get { return this.органЗАГСField; }
            set { this.органЗАГСField = value; }
        }

        /// <remarks/>
        public СтатусЗаписиТип СтатусЗаписи
        {
            get { return this.статусЗаписиField; }
            set { this.статусЗаписиField = value; }
        }

        /// <remarks/>
        public СведСвидетТип СведСвидет
        {
            get { return this.сведСвидетField; }
            set { this.сведСвидетField = value; }
        }

        /// <remarks/>
        public informResponseСвеРегОтцовПрдСведРег ПрдСведРег
        {
            get { return this.прдСведРегField; }
            set { this.прдСведРегField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерЗапис
        {
            get { return this.номерЗаписField; }
            set { this.номерЗаписField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаЗапис
        {
            get { return this.датаЗаписField; }
            set { this.датаЗаписField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСвеРегОтцовПрдСведРег
    {

        private informResponseСвеРегОтцовПрдСведРегСведРебенок сведРебенокField;

        private СведРодитТип сведМатьField;

        private СведРодитТип сведОтецField;

        private informResponseСвеРегОтцовПрдСведРегСведДокОсн сведДокОснField;

        /// <remarks/>
        public informResponseСвеРегОтцовПрдСведРегСведРебенок СведРебенок
        {
            get { return this.сведРебенокField; }
            set { this.сведРебенокField = value; }
        }

        /// <remarks/>
        public СведРодитТип СведМать
        {
            get { return this.сведМатьField; }
            set { this.сведМатьField = value; }
        }

        /// <remarks/>
        public СведРодитТип СведОтец
        {
            get { return this.сведОтецField; }
            set { this.сведОтецField = value; }
        }

        /// <remarks/>
        public informResponseСвеРегОтцовПрдСведРегСведДокОсн СведДокОсн
        {
            get { return this.сведДокОснField; }
            set { this.сведДокОснField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСвеРегОтцовПрдСведРегСведРебенок
    {

        private ФИОПрТип фИОДоField;

        private ФИОПрТип фИОПослеField;

        private object itemField;

        private ItemChoiceType3 itemElementNameField;

        private МестоТип местоРожденField;

        private informResponseСвеРегОтцовПрдСведРегСведРебенокСведРегРожд сведРегРождField;

        private СведСвидетТип[] сведСвидетРождField;

        private informResponseСвеРегОтцовПрдСведРегСведРебенокПол полField;

        /// <remarks/>
        public ФИОПрТип ФИОДо
        {
            get { return this.фИОДоField; }
            set { this.фИОДоField = value; }
        }

        /// <remarks/>
        public ФИОПрТип ФИОПосле
        {
            get { return this.фИОПослеField; }
            set { this.фИОПослеField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГодРожд", typeof(string), DataType = "gYear")]
        [System.Xml.Serialization.XmlElementAttribute("ДатаРожд", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("МесГодРожд", typeof(string), DataType = "gYearMonth")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType3 ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }

        /// <remarks/>
        public МестоТип МестоРожден
        {
            get { return this.местоРожденField; }
            set { this.местоРожденField = value; }
        }

        /// <remarks/>
        public informResponseСвеРегОтцовПрдСведРегСведРебенокСведРегРожд СведРегРожд
        {
            get { return this.сведРегРождField; }
            set { this.сведРегРождField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведСвидетРожд")]
        public СведСвидетТип[] СведСвидетРожд
        {
            get { return this.сведСвидетРождField; }
            set { this.сведСвидетРождField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public informResponseСвеРегОтцовПрдСведРегСведРебенокПол Пол
        {
            get { return this.полField; }
            set { this.полField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4",
        IncludeInSchema = false)]
    public enum ItemChoiceType3
    {

        /// <remarks/>
        ГодРожд,

        /// <remarks/>
        ДатаРожд,

        /// <remarks/>
        МесГодРожд,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСвеРегОтцовПрдСведРегСведРебенокСведРегРожд
    {

        private ОрганЗАГСТип органЗАГСРождField;

        private string номерЗаписField;

        private System.DateTime датаЗаписField;

        /// <remarks/>
        public ОрганЗАГСТип ОрганЗАГСРожд
        {
            get { return this.органЗАГСРождField; }
            set { this.органЗАГСРождField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерЗапис
        {
            get { return this.номерЗаписField; }
            set { this.номерЗаписField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаЗапис
        {
            get { return this.датаЗаписField; }
            set { this.датаЗаписField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public enum informResponseСвеРегОтцовПрдСведРегСведРебенокПол
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСвеРегОтцовПрдСведРегСведДокОсн
    {

        private string кодДокField;

        private string наимДокField;

        private string наимСудРешField;

        private string серНомДокField;

        private System.DateTime датаДокField;

        private bool датаДокFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодДок
        {
            get { return this.кодДокField; }
            set { this.кодДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДок
        {
            get { return this.наимДокField; }
            set { this.наимДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимСудРеш
        {
            get { return this.наимСудРешField; }
            set { this.наимСудРешField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СерНомДок
        {
            get { return this.серНомДокField; }
            set { this.серНомДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаДок
        {
            get { return this.датаДокField; }
            set { this.датаДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДатаДокSpecified
        {
            get { return this.датаДокFieldSpecified; }
            set { this.датаДокFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегПерИмя
    {

        private ОрганЗАГСТип органЗАГСField;

        private СтатусЗаписиТип статусЗаписиField;

        private СведСвидетТип сведСвидетField;

        private informResponseСведРегПерИмяПрдСведРег прдСведРегField;

        private string номерЗаписField;

        private System.DateTime датаЗаписField;

        /// <remarks/>
        public ОрганЗАГСТип ОрганЗАГС
        {
            get { return this.органЗАГСField; }
            set { this.органЗАГСField = value; }
        }

        /// <remarks/>
        public СтатусЗаписиТип СтатусЗаписи
        {
            get { return this.статусЗаписиField; }
            set { this.статусЗаписиField = value; }
        }

        /// <remarks/>
        public СведСвидетТип СведСвидет
        {
            get { return this.сведСвидетField; }
            set { this.сведСвидетField = value; }
        }

        /// <remarks/>
        public informResponseСведРегПерИмяПрдСведРег ПрдСведРег
        {
            get { return this.прдСведРегField; }
            set { this.прдСведРегField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерЗапис
        {
            get { return this.номерЗаписField; }
            set { this.номерЗаписField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаЗапис
        {
            get { return this.датаЗаписField; }
            set { this.датаЗаписField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегПерИмяПрдСведРег
    {

        private ФИОПрТип фИОДоField;

        private ФИОПрТип фИОПослеField;

        private object itemField;

        private ItemChoiceType4 itemElementNameField;

        private МестоТип местоРожденField;

        private object item1Field;

        private УдЛичнФЛТип удЛичнФЛField;

        private string оКСМField;

        private string наимСтраныField;

        /// <remarks/>
        public ФИОПрТип ФИОДо
        {
            get { return this.фИОДоField; }
            set { this.фИОДоField = value; }
        }

        /// <remarks/>
        public ФИОПрТип ФИОПосле
        {
            get { return this.фИОПослеField; }
            set { this.фИОПослеField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГодРожд", typeof(string), DataType = "gYear")]
        [System.Xml.Serialization.XmlElementAttribute("ДатаРожд", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("МесГодРожд", typeof(string), DataType = "gYearMonth")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType4 ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }

        /// <remarks/>
        public МестоТип МестоРожден
        {
            get { return this.местоРожденField; }
            set { this.местоРожденField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрМЖИн", typeof(АдрМЖИнТип))]
        [System.Xml.Serialization.XmlElementAttribute("АдрМЖРФ", typeof(АдрМЖРФТип))]
        public object Item1
        {
            get { return this.item1Field; }
            set { this.item1Field = value; }
        }

        /// <remarks/>
        public УдЛичнФЛТип УдЛичнФЛ
        {
            get { return this.удЛичнФЛField; }
            set { this.удЛичнФЛField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКСМ
        {
            get { return this.оКСМField; }
            set { this.оКСМField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимСтраны
        {
            get { return this.наимСтраныField; }
            set { this.наимСтраныField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4",
        IncludeInSchema = false)]
    public enum ItemChoiceType4
    {

        /// <remarks/>
        ГодРожд,

        /// <remarks/>
        ДатаРожд,

        /// <remarks/>
        МесГодРожд,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегСмерт
    {

        private ОрганЗАГСТип органЗАГСField;

        private СтатусЗаписиТип статусЗаписиField;

        private СведСвидетТип сведСвидетField;

        private informResponseСведРегСмертПрдСведРег прдСведРегField;

        private string номерЗаписField;

        private System.DateTime датаЗаписField;

        /// <remarks/>
        public ОрганЗАГСТип ОрганЗАГС
        {
            get { return this.органЗАГСField; }
            set { this.органЗАГСField = value; }
        }

        /// <remarks/>
        public СтатусЗаписиТип СтатусЗаписи
        {
            get { return this.статусЗаписиField; }
            set { this.статусЗаписиField = value; }
        }

        /// <remarks/>
        public СведСвидетТип СведСвидет
        {
            get { return this.сведСвидетField; }
            set { this.сведСвидетField = value; }
        }

        /// <remarks/>
        public informResponseСведРегСмертПрдСведРег ПрдСведРег
        {
            get { return this.прдСведРегField; }
            set { this.прдСведРегField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерЗапис
        {
            get { return this.номерЗаписField; }
            set { this.номерЗаписField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаЗапис
        {
            get { return this.датаЗаписField; }
            set { this.датаЗаписField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегСмертПрдСведРег
    {

        private informResponseСведРегСмертПрдСведРегСведУмер сведУмерField;

        private informResponseСведРегСмертПрдСведРегСведДокСмерт сведДокСмертField;

        /// <remarks/>
        public informResponseСведРегСмертПрдСведРегСведУмер СведУмер
        {
            get { return this.сведУмерField; }
            set { this.сведУмерField = value; }
        }

        /// <remarks/>
        public informResponseСведРегСмертПрдСведРегСведДокСмерт СведДокСмерт
        {
            get { return this.сведДокСмертField; }
            set { this.сведДокСмертField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегСмертПрдСведРегСведУмер
    {

        private informResponseСведРегСмертПрдСведРегСведУмерСведПричСмерт[] сведПричСмертField;

        private ФИОПрТип фИОУмерField;

        private object itemField;

        private ItemChoiceType5 itemElementNameField;

        private МестоТип местоРожденField;

        private object item1Field;

        private УдЛичнФЛТип удЛичнФЛField;

        private object item2Field;

        private Item2ChoiceType item2ElementNameField;

        private МестоТип местоСмертField;

        private informResponseСведРегСмертПрдСведРегСведУмерПол полField;

        private string оКСМField;

        private string наимСтраныField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведПричСмерт")]
        public informResponseСведРегСмертПрдСведРегСведУмерСведПричСмерт[] СведПричСмерт
        {
            get { return this.сведПричСмертField; }
            set { this.сведПричСмертField = value; }
        }

        /// <remarks/>
        public ФИОПрТип ФИОУмер
        {
            get { return this.фИОУмерField; }
            set { this.фИОУмерField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГодРожд", typeof(string), DataType = "gYear")]
        [System.Xml.Serialization.XmlElementAttribute("ДатаРожд", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("МесГодРожд", typeof(string), DataType = "gYearMonth")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType5 ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }

        /// <remarks/>
        public МестоТип МестоРожден
        {
            get { return this.местоРожденField; }
            set { this.местоРожденField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("МЖПослИн", typeof(АдрМЖИнТип))]
        [System.Xml.Serialization.XmlElementAttribute("МЖПослРФ", typeof(АдрМЖРФТип))]
        public object Item1
        {
            get { return this.item1Field; }
            set { this.item1Field = value; }
        }

        /// <remarks/>
        public УдЛичнФЛТип УдЛичнФЛ
        {
            get { return this.удЛичнФЛField; }
            set { this.удЛичнФЛField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГодСмерт", typeof(string), DataType = "gYear")]
        [System.Xml.Serialization.XmlElementAttribute("ДатаСмерт", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("МесГодСмерт", typeof(string), DataType = "gYearMonth")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item2ElementName")]
        public object Item2
        {
            get { return this.item2Field; }
            set { this.item2Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Item2ChoiceType Item2ElementName
        {
            get { return this.item2ElementNameField; }
            set { this.item2ElementNameField = value; }
        }

        /// <remarks/>
        public МестоТип МестоСмерт
        {
            get { return this.местоСмертField; }
            set { this.местоСмертField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public informResponseСведРегСмертПрдСведРегСведУмерПол Пол
        {
            get { return this.полField; }
            set { this.полField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКСМ
        {
            get { return this.оКСМField; }
            set { this.оКСМField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимСтраны
        {
            get { return this.наимСтраныField; }
            set { this.наимСтраныField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегСмертПрдСведРегСведУмерСведПричСмерт
    {

        private string кодПричСмертField;

        private string причСмертField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодПричСмерт
        {
            get { return this.кодПричСмертField; }
            set { this.кодПричСмертField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ПричСмерт
        {
            get { return this.причСмертField; }
            set { this.причСмертField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4",
        IncludeInSchema = false)]
    public enum ItemChoiceType5
    {

        /// <remarks/>
        ГодРожд,

        /// <remarks/>
        ДатаРожд,

        /// <remarks/>
        МесГодРожд,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4",
        IncludeInSchema = false)]
    public enum Item2ChoiceType
    {

        /// <remarks/>
        ГодСмерт,

        /// <remarks/>
        ДатаСмерт,

        /// <remarks/>
        МесГодСмерт,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public enum informResponseСведРегСмертПрдСведРегСведУмерПол
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public partial class informResponseСведРегСмертПрдСведРегСведДокСмерт
    {

        private object itemField;

        private ItemChoiceType6 itemElementNameField;

        private string кодДокField;

        private string наимДокField;

        private string серНомДокField;

        private System.DateTime датаДокField;

        private bool датаДокFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НаимОрг", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ФИОИП", typeof(ФИОПрТип))]
        [System.Xml.Serialization.XmlElementAttribute("ФИОФЛ", typeof(ФИОПрТип))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType6 ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодДок
        {
            get { return this.кодДокField; }
            set { this.кодДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимДок
        {
            get { return this.наимДокField; }
            set { this.наимДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СерНомДок
        {
            get { return this.серНомДокField; }
            set { this.серНомДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаДок
        {
            get { return this.датаДокField; }
            set { this.датаДокField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДатаДокSpecified
        {
            get { return this.датаДокFieldSpecified; }
            set { this.датаДокFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4",
        IncludeInSchema = false)]
    public enum ItemChoiceType6
    {

        /// <remarks/>
        НаимОрг,

        /// <remarks/>
        ФИОИП,

        /// <remarks/>
        ФИОФЛ,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public enum informResponseТипЗапрос
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public enum informResponseТипАГСЗапрос
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public enum informResponseРезОбраб
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "urn://x-artefacts-zags-inform/root/112-11/4.0.4")]
    public enum informResponseКодСтатус
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
    }
}
