//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 

namespace RestChild.Comon.Exchange.EGRZagz
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1", IsNullable = false)]
    public partial class ROGDINFResponse
    {

        private ROGDINFResponseСведОтветАГС[] сведОтветАГСField;

        private string идЗапросField;

        private System.DateTime датаСведField;

        private string колДокField;

        private ROGDINFResponseТипАГСЗапрос типАГСЗапросField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведОтветАГС")]
        public ROGDINFResponseСведОтветАГС[] СведОтветАГС
        {
            get
            {
                return this.сведОтветАГСField;
            }
            set
            {
                this.сведОтветАГСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдЗапрос
        {
            get
            {
                return this.идЗапросField;
            }
            set
            {
                this.идЗапросField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаСвед
        {
            get
            {
                return this.датаСведField;
            }
            set
            {
                this.датаСведField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string КолДок
        {
            get
            {
                return this.колДокField;
            }
            set
            {
                this.колДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ROGDINFResponseТипАГСЗапрос ТипАГСЗапрос
        {
            get
            {
                return this.типАГСЗапросField;
            }
            set
            {
                this.типАГСЗапросField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public partial class ROGDINFResponseСведОтветАГС
    {

        private ROGDINFResponseСведОтветАГССведРегРожд[] сведРегРождField;

        private string идДокField;

        private ROGDINFResponseСведОтветАГСРезОбраб резОбрабField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведРегРожд")]
        public ROGDINFResponseСведОтветАГССведРегРожд[] СведРегРожд
        {
            get
            {
                return this.сведРегРождField;
            }
            set
            {
                this.сведРегРождField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдДок
        {
            get
            {
                return this.идДокField;
            }
            set
            {
                this.идДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ROGDINFResponseСведОтветАГСРезОбраб РезОбраб
        {
            get
            {
                return this.резОбрабField;
            }
            set
            {
                this.резОбрабField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public partial class ROGDINFResponseСведОтветАГССведРегРожд
    {

        private object itemField;

        private ОрганЗАГСТип органЗАГСField;

        private СведСвидетТип[] свидетРождField;

        private ROGDINFResponseСведОтветАГССведРегРождПрдСведРег прдСведРегField;

        private СведЕГРРазд2Тип сВедЕГРРазд2Field;

        private ROGDINFResponseСведОтветАГССведРегРождРазделЕГР разделЕГРField;

        private string номерЗаписЕГРField;

        private string номАГССвидField;

        private string номерВерсField;

        private System.DateTime датаВерсField;

        private string кодСостСтатField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДатаЗапис", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("ДатаЗаписДок", typeof(ДатаДокТип))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public ОрганЗАГСТип ОрганЗАГС
        {
            get
            {
                return this.органЗАГСField;
            }
            set
            {
                this.органЗАГСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвидетРожд")]
        public СведСвидетТип[] СвидетРожд
        {
            get
            {
                return this.свидетРождField;
            }
            set
            {
                this.свидетРождField = value;
            }
        }

        /// <remarks/>
        public ROGDINFResponseСведОтветАГССведРегРождПрдСведРег ПрдСведРег
        {
            get
            {
                return this.прдСведРегField;
            }
            set
            {
                this.прдСведРегField = value;
            }
        }

        /// <remarks/>
        public СведЕГРРазд2Тип СВедЕГРРазд2
        {
            get
            {
                return this.сВедЕГРРазд2Field;
            }
            set
            {
                this.сВедЕГРРазд2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ROGDINFResponseСведОтветАГССведРегРождРазделЕГР РазделЕГР
        {
            get
            {
                return this.разделЕГРField;
            }
            set
            {
                this.разделЕГРField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерЗаписЕГР
        {
            get
            {
                return this.номерЗаписЕГРField;
            }
            set
            {
                this.номерЗаписЕГРField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомАГССвид
        {
            get
            {
                return this.номАГССвидField;
            }
            set
            {
                this.номАГССвидField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерВерс
        {
            get
            {
                return this.номерВерсField;
            }
            set
            {
                this.номерВерсField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаВерс
        {
            get
            {
                return this.датаВерсField;
            }
            set
            {
                this.датаВерсField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодСостСтат
        {
            get
            {
                return this.кодСостСтатField;
            }
            set
            {
                this.кодСостСтатField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class ДатаДокТип
    {

        private object itemField;

        private object item1Field;

        private string годField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("День", typeof(string), DataType = "integer")]
        [System.Xml.Serialization.XmlElementAttribute("ПрДень", typeof(ДатаДокТипПрДень))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Месяц", typeof(string), DataType = "integer")]
        [System.Xml.Serialization.XmlElementAttribute("ПрМесяц", typeof(ДатаДокТипПрМесяц))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "gYear")]
        public string Год
        {
            get
            {
                return this.годField;
            }
            set
            {
                this.годField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum ДатаДокТипПрДень
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum ДатаДокТипПрМесяц
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class ЗасвидТип
    {

        private string регНомРеестрНотарField;

        private System.DateTime датаНотарДействField;

        private string фИОНотарField;

        private string фИОПереводField;

        private string колЛистДокField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string РегНомРеестрНотар
        {
            get
            {
                return this.регНомРеестрНотарField;
            }
            set
            {
                this.регНомРеестрНотарField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаНотарДейств
        {
            get
            {
                return this.датаНотарДействField;
            }
            set
            {
                this.датаНотарДействField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ФИОНотар
        {
            get
            {
                return this.фИОНотарField;
            }
            set
            {
                this.фИОНотарField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ФИОПеревод
        {
            get
            {
                return this.фИОПереводField;
            }
            set
            {
                this.фИОПереводField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string КолЛистДок
        {
            get
            {
                return this.колЛистДокField;
            }
            set
            {
                this.колЛистДокField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class СведЕГРРазд2Тип
    {

        private object itemField;

        private СведЕГРРазд2ТипСвДокИн свДокИнField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрСвУведомл", typeof(СведЕГРРазд2ТипПрСвУведомл))]
        [System.Xml.Serialization.XmlElementAttribute("СвУведомл", typeof(СведЕГРРазд2ТипСвУведомл))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public СведЕГРРазд2ТипСвДокИн СвДокИн
        {
            get
            {
                return this.свДокИнField;
            }
            set
            {
                this.свДокИнField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипПрСвУведомл
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class СведЕГРРазд2ТипСвУведомл
    {

        private object itemField;

        private object item1Field;

        private СведЕГРРазд2ТипСвУведомлСведЗАГСУвед сведЗАГСУведField;

        private СведЕГРРазд2ТипСвУведомлСпоcПод споcПодField;

        private string колЛистДокField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КодВидУвед", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрКодВидУвед", typeof(СведЕГРРазд2ТипСвУведомлПрКодВидУвед))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДатаУвед", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("ПрДатаУвед", typeof(СведЕГРРазд2ТипСвУведомлПрДатаУвед))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <remarks/>
        public СведЕГРРазд2ТипСвУведомлСведЗАГСУвед СведЗАГСУвед
        {
            get
            {
                return this.сведЗАГСУведField;
            }
            set
            {
                this.сведЗАГСУведField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СведЕГРРазд2ТипСвУведомлСпоcПод СпоcПод
        {
            get
            {
                return this.споcПодField;
            }
            set
            {
                this.споcПодField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string КолЛистДок
        {
            get
            {
                return this.колЛистДокField;
            }
            set
            {
                this.колЛистДокField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвУведомлПрКодВидУвед
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвУведомлПрДатаУвед
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class СведЕГРРазд2ТипСвУведомлСведЗАГСУвед
    {

        private ОрганЗАГСТип органЗАГСField;

        private object itemField;

        private System.DateTime датаПринятField;

        private string должнОтвField;

        /// <remarks/>
        public ОрганЗАГСТип ОрганЗАГС
        {
            get
            {
                return this.органЗАГСField;
            }
            set
            {
                this.органЗАГСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрФИООтв", typeof(СведЕГРРазд2ТипСвУведомлСведЗАГСУведПрФИООтв))]
        [System.Xml.Serialization.XmlElementAttribute("ФИООтв", typeof(ФИОПрТип))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime ДатаПринят
        {
            get
            {
                return this.датаПринятField;
            }
            set
            {
                this.датаПринятField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДолжнОтв
        {
            get
            {
                return this.должнОтвField;
            }
            set
            {
                this.должнОтвField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class ОрганЗАГСТип
    {

        private string наимЗАГСField;

        private string кодЗАГСField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимЗАГС
        {
            get
            {
                return this.наимЗАГСField;
            }
            set
            {
                this.наимЗАГСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодЗАГС
        {
            get
            {
                return this.кодЗАГСField;
            }
            set
            {
                this.кодЗАГСField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвУведомлСведЗАГСУведПрФИООтв
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class ФИОПрТип
    {

        private object itemField;

        private object item1Field;

        private object item2Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрФамилия", typeof(ФИОПрТипПрФамилия))]
        [System.Xml.Serialization.XmlElementAttribute("Фамилия", typeof(string))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Имя", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрИмя", typeof(ФИОПрТипПрИмя))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Отчество", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрОтчество", typeof(ФИОПрТипПрОтчество))]
        public object Item2
        {
            get
            {
                return this.item2Field;
            }
            set
            {
                this.item2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum ФИОПрТипПрФамилия
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum ФИОПрТипПрИмя
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum ФИОПрТипПрОтчество
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвУведомлСпоcПод
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class СведЕГРРазд2ТипСвДокИн
    {

        private object itemField;

        private string наимСтраныField;

        private СведЕГРРазд2ТипСвДокИнРеквизИнДок реквизИнДокField;

        private СведЕГРРазд2ТипСвДокИнЮрЗначДок юрЗначДокField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КодОКСМ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрКодОКСМ", typeof(СведЕГРРазд2ТипСвДокИнПрКодОКСМ))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public string НаимСтраны
        {
            get
            {
                return this.наимСтраныField;
            }
            set
            {
                this.наимСтраныField = value;
            }
        }

        /// <remarks/>
        public СведЕГРРазд2ТипСвДокИнРеквизИнДок РеквизИнДок
        {
            get
            {
                return this.реквизИнДокField;
            }
            set
            {
                this.реквизИнДокField = value;
            }
        }

        /// <remarks/>
        public СведЕГРРазд2ТипСвДокИнЮрЗначДок ЮрЗначДок
        {
            get
            {
                return this.юрЗначДокField;
            }
            set
            {
                this.юрЗначДокField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнПрКодОКСМ
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class СведЕГРРазд2ТипСвДокИнРеквизИнДок
    {

        private object itemField;

        private object item1Field;

        private object item2Field;

        private object item3Field;

        private string типДокField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НаимДокТекст", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрНаимДокТекст", typeof(СведЕГРРазд2ТипСвДокИнРеквизИнДокПрНаимДокТекст))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Номер", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрНомер", typeof(СведЕГРРазд2ТипСвДокИнРеквизИнДокПрНомер))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДатаДок", typeof(ДатаДокТип))]
        [System.Xml.Serialization.XmlElementAttribute("ДатаКаленд", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("ПрДата", typeof(СведЕГРРазд2ТипСвДокИнРеквизИнДокПрДата))]
        public object Item2
        {
            get
            {
                return this.item2Field;
            }
            set
            {
                this.item2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НаимОрган", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрНаимОрган", typeof(СведЕГРРазд2ТипСвДокИнРеквизИнДокПрНаимОрган))]
        public object Item3
        {
            get
            {
                return this.item3Field;
            }
            set
            {
                this.item3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ТипДок
        {
            get
            {
                return this.типДокField;
            }
            set
            {
                this.типДокField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнРеквизИнДокПрНаимДокТекст
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнРеквизИнДокПрНомер
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнРеквизИнДокПрДата
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнРеквизИнДокПрНаимОрган
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class СведЕГРРазд2ТипСвДокИнЮрЗначДок
    {

        private object itemField;

        private object item1Field;

        private object item2Field;

        private object item3Field;

        private string колЛистДокField;

        private СведЕГРРазд2ТипСвДокИнЮрЗначДокСвОттискПеч свОттискПечField;

        private СведЕГРРазд2ТипСвДокИнЮрЗначДокСвЛегал свЛегалField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрПодпИн", typeof(СведЕГРРазд2ТипСвДокИнЮрЗначДокПрПодпИн))]
        [System.Xml.Serialization.XmlElementAttribute("СвПодпТекст", typeof(string))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ЗасвидДок", typeof(ЗасвидТип))]
        [System.Xml.Serialization.XmlElementAttribute("ПрЗасвидДок", typeof(СведЕГРРазд2ТипСвДокИнЮрЗначДокПрЗасвидДок))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ЗасвидПеревод", typeof(ЗасвидТип))]
        [System.Xml.Serialization.XmlElementAttribute("ПрЗасвидПеревод", typeof(СведЕГРРазд2ТипСвДокИнЮрЗначДокПрЗасвидПеревод))]
        public object Item2
        {
            get
            {
                return this.item2Field;
            }
            set
            {
                this.item2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Легализация", typeof(СведЕГРРазд2ТипСвДокИнЮрЗначДокЛегализация))]
        [System.Xml.Serialization.XmlElementAttribute("СвОтказЛегализ", typeof(СведЕГРРазд2ТипСвДокИнЮрЗначДокСвОтказЛегализ))]
        public object Item3
        {
            get
            {
                return this.item3Field;
            }
            set
            {
                this.item3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string КолЛистДок
        {
            get
            {
                return this.колЛистДокField;
            }
            set
            {
                this.колЛистДокField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СведЕГРРазд2ТипСвДокИнЮрЗначДокСвОттискПеч СвОттискПеч
        {
            get
            {
                return this.свОттискПечField;
            }
            set
            {
                this.свОттискПечField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СведЕГРРазд2ТипСвДокИнЮрЗначДокСвЛегал СвЛегал
        {
            get
            {
                return this.свЛегалField;
            }
            set
            {
                this.свЛегалField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнЮрЗначДокПрПодпИн
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнЮрЗначДокПрЗасвидДок
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнЮрЗначДокПрЗасвидПеревод
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class СведЕГРРазд2ТипСвДокИнЮрЗначДокЛегализация
    {

        private object itemField;

        private object item1Field;

        private object item2Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОрганЛегал", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрОрганЛегал", typeof(СведЕГРРазд2ТипСвДокИнЮрЗначДокЛегализацияПрОрганЛегал))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДатаЛегал", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("ПрДатаЛегал", typeof(СведЕГРРазд2ТипСвДокИнЮрЗначДокЛегализацияПрДатаЛегал))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НомерЛегал", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрНомерЛегал", typeof(СведЕГРРазд2ТипСвДокИнЮрЗначДокЛегализацияПрНомерЛегал))]
        public object Item2
        {
            get
            {
                return this.item2Field;
            }
            set
            {
                this.item2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнЮрЗначДокЛегализацияПрОрганЛегал
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнЮрЗначДокЛегализацияПрДатаЛегал
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнЮрЗначДокЛегализацияПрНомерЛегал
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнЮрЗначДокСвОтказЛегализ
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнЮрЗначДокСвОттискПеч
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведЕГРРазд2ТипСвДокИнЮрЗначДокСвЛегал
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class СведДокТип
    {

        private object itemField;

        private ItemChoiceType2 itemElementNameField;

        private object item1Field;

        private object item2Field;

        private object item3Field;

        private Item3ChoiceType item3ElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КодДок", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("НаимДок", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрДок", typeof(СведДокТипПрДок))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрСерНомДок", typeof(СведДокТипПрСерНомДок))]
        [System.Xml.Serialization.XmlElementAttribute("СерНомДок", typeof(string))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДатаДокКаленд", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("ДатаДокНеполн", typeof(ДатаДокТип))]
        [System.Xml.Serialization.XmlElementAttribute("ПрДатаДок", typeof(СведДокТипПрДатаДок))]
        public object Item2
        {
            get
            {
                return this.item2Field;
            }
            set
            {
                this.item2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НаимОрг", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрОргФИО", typeof(СведДокТипПрОргФИО))]
        [System.Xml.Serialization.XmlElementAttribute("ФИОИП", typeof(ФИОПрТип))]
        [System.Xml.Serialization.XmlElementAttribute("ФИОФЛ", typeof(ФИОПрТип))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item3ElementName")]
        public object Item3
        {
            get
            {
                return this.item3Field;
            }
            set
            {
                this.item3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Item3ChoiceType Item3ElementName
        {
            get
            {
                return this.item3ElementNameField;
            }
            set
            {
                this.item3ElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведДокТипПрДок
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1", IncludeInSchema = false)]
    public enum ItemChoiceType2
    {

        /// <remarks/>
        КодДок,

        /// <remarks/>
        НаимДок,

        /// <remarks/>
        ПрДок,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведДокТипПрСерНомДок
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведДокТипПрДатаДок
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведДокТипПрОргФИО
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1", IncludeInSchema = false)]
    public enum Item3ChoiceType
    {

        /// <remarks/>
        НаимОрг,

        /// <remarks/>
        ПрОргФИО,

        /// <remarks/>
        ФИОИП,

        /// <remarks/>
        ФИОФЛ,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class ЗапАктТип
    {

        private object itemField;

        private ОрганЗАГСТип органЗАГСField;

        private string типАГСField;

        private string номерЗаписField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДатаЗапис", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("ДатаЗаписДок", typeof(ДатаДокТип))]
        [System.Xml.Serialization.XmlElementAttribute("ПрДатаЗапис", typeof(ЗапАктТипПрДатаЗапис))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public ОрганЗАГСТип ОрганЗАГС
        {
            get
            {
                return this.органЗАГСField;
            }
            set
            {
                this.органЗАГСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ТипАГС
        {
            get
            {
                return this.типАГСField;
            }
            set
            {
                this.типАГСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерЗапис
        {
            get
            {
                return this.номерЗаписField;
            }
            set
            {
                this.номерЗаписField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum ЗапАктТипПрДатаЗапис
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class СведДокОснТип
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДокОсн", typeof(СведДокТип))]
        [System.Xml.Serialization.XmlElementAttribute("ЗапАктОсн", typeof(ЗапАктТип))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class АдрРФТип
    {

        private string адрТекстField;

        private string идНомField;

        private string оКТМОField;

        private string индексField;

        private string кодРегионField;

        private string наимРегионField;

        private string районField;

        private string городField;

        private string населПунктField;

        private string улицаField;

        private string домField;

        private string корпусField;

        private string квартField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АдрТекст
        {
            get
            {
                return this.адрТекстField;
            }
            set
            {
                this.адрТекстField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдНом
        {
            get
            {
                return this.идНомField;
            }
            set
            {
                this.идНомField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКТМО
        {
            get
            {
                return this.оКТМОField;
            }
            set
            {
                this.оКТМОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Индекс
        {
            get
            {
                return this.индексField;
            }
            set
            {
                this.индексField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодРегион
        {
            get
            {
                return this.кодРегионField;
            }
            set
            {
                this.кодРегионField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимРегион
        {
            get
            {
                return this.наимРегионField;
            }
            set
            {
                this.наимРегионField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Район
        {
            get
            {
                return this.районField;
            }
            set
            {
                this.районField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Город
        {
            get
            {
                return this.городField;
            }
            set
            {
                this.городField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаселПункт
        {
            get
            {
                return this.населПунктField;
            }
            set
            {
                this.населПунктField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Улица
        {
            get
            {
                return this.улицаField;
            }
            set
            {
                this.улицаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Дом
        {
            get
            {
                return this.домField;
            }
            set
            {
                this.домField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Корпус
        {
            get
            {
                return this.корпусField;
            }
            set
            {
                this.корпусField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Кварт
        {
            get
            {
                return this.квартField;
            }
            set
            {
                this.квартField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class АдрМЖТип
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрМЖИн", typeof(АдрМЖТипАдрМЖИн))]
        [System.Xml.Serialization.XmlElementAttribute("АдрМЖКонв", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("АдрМЖРФ", typeof(АдрМЖТипАдрМЖРФ))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class АдрМЖТипАдрМЖИн
    {

        private object itemField;

        private string адрТекстField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОКСМ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрОКСМ", typeof(АдрМЖТипАдрМЖИнПрОКСМ))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public string АдрТекст
        {
            get
            {
                return this.адрТекстField;
            }
            set
            {
                this.адрТекстField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum АдрМЖТипАдрМЖИнПрОКСМ
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class АдрМЖТипАдрМЖРФ
    {

        private object itemField;

        private ItemChoiceType1 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрРФНеФИАС", typeof(АдрРФТип))]
        [System.Xml.Serialization.XmlElementAttribute("АдрРФФИАС", typeof(АдрРФТип))]
        [System.Xml.Serialization.XmlElementAttribute("АдрТекст", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1", IncludeInSchema = false)]
    public enum ItemChoiceType1
    {

        /// <remarks/>
        АдрРФНеФИАС,

        /// <remarks/>
        АдрРФФИАС,

        /// <remarks/>
        АдрТекст,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class УдЛичнФЛПрТип
    {

        private object itemField;

        private object item1Field;

        private object item2Field;

        private object item3Field;

        private object item4Field;

        private object item5Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КодВидДок", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрКодВидДок", typeof(УдЛичнФЛПрТипПрКодВидДок))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрСерДок", typeof(УдЛичнФЛПрТипПрСерДок))]
        [System.Xml.Serialization.XmlElementAttribute("СерДок", typeof(string))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НомДок", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрНомДок", typeof(УдЛичнФЛПрТипПрНомДок))]
        public object Item2
        {
            get
            {
                return this.item2Field;
            }
            set
            {
                this.item2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДатаДокКаленд", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("ДатаДокНеполн", typeof(ДатаДокТип))]
        [System.Xml.Serialization.XmlElementAttribute("ПрДатаДок", typeof(УдЛичнФЛПрТипПрДатаДок))]
        public object Item3
        {
            get
            {
                return this.item3Field;
            }
            set
            {
                this.item3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ВыдДок", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрВыдДок", typeof(УдЛичнФЛПрТипПрВыдДок))]
        public object Item4
        {
            get
            {
                return this.item4Field;
            }
            set
            {
                this.item4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КодВыдДок", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрКодВыдДок", typeof(УдЛичнФЛПрТипПрКодВыдДок))]
        public object Item5
        {
            get
            {
                return this.item5Field;
            }
            set
            {
                this.item5Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum УдЛичнФЛПрТипПрКодВидДок
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum УдЛичнФЛПрТипПрСерДок
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum УдЛичнФЛПрТипПрНомДок
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum УдЛичнФЛПрТипПрДатаДок
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum УдЛичнФЛПрТипПрВыдДок
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum УдЛичнФЛПрТипПрКодВыдДок
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class СведРодитТип
    {

        private object itemField;

        private ItemChoiceType itemElementNameField;

        private ФИОПрТип фИОField;

        private object item1Field;

        private object item2Field;

        private object item3Field;

        private object item4Field;

        private string сНИЛСField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГраждОКСМ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ГраждТекст", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрГражданство", typeof(СведРодитТипПрГражданство))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        public ФИОПрТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДатаРождДок", typeof(ДатаДокТип))]
        [System.Xml.Serialization.XmlElementAttribute("ДатаРождКаленд", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("ПрДатаРожд", typeof(СведРодитТипПрДатаРожд))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("МестоРожден", typeof(МестоТип))]
        [System.Xml.Serialization.XmlElementAttribute("ПрМестоРожден", typeof(СведРодитТипПрМестоРожден))]
        public object Item2
        {
            get
            {
                return this.item2Field;
            }
            set
            {
                this.item2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрУдЛичнФЛ", typeof(СведРодитТипПрУдЛичнФЛ))]
        [System.Xml.Serialization.XmlElementAttribute("УдЛичнФЛ", typeof(УдЛичнФЛПрТип))]
        public object Item3
        {
            get
            {
                return this.item3Field;
            }
            set
            {
                this.item3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрМЖ", typeof(АдрМЖТип))]
        [System.Xml.Serialization.XmlElementAttribute("ПрАдрМЖ", typeof(СведРодитТипПрАдрМЖ))]
        public object Item4
        {
            get
            {
                return this.item4Field;
            }
            set
            {
                this.item4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СНИЛС
        {
            get
            {
                return this.сНИЛСField;
            }
            set
            {
                this.сНИЛСField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведРодитТипПрГражданство
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        ГраждОКСМ,

        /// <remarks/>
        ГраждТекст,

        /// <remarks/>
        ПрГражданство,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведРодитТипПрДатаРожд
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class МестоТип
    {

        private МестоТипПризнМесто признМестоField;

        private string местоТекстField;

        private string кодСтраныField;

        private string наимСтраныField;

        private string регионField;

        private string наимСубъектField;

        private string районField;

        private string городField;

        private string населПунктField;

        private string оКТМОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public МестоТипПризнМесто ПризнМесто
        {
            get
            {
                return this.признМестоField;
            }
            set
            {
                this.признМестоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string МестоТекст
        {
            get
            {
                return this.местоТекстField;
            }
            set
            {
                this.местоТекстField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодСтраны
        {
            get
            {
                return this.кодСтраныField;
            }
            set
            {
                this.кодСтраныField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимСтраны
        {
            get
            {
                return this.наимСтраныField;
            }
            set
            {
                this.наимСтраныField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Регион
        {
            get
            {
                return this.регионField;
            }
            set
            {
                this.регионField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимСубъект
        {
            get
            {
                return this.наимСубъектField;
            }
            set
            {
                this.наимСубъектField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Район
        {
            get
            {
                return this.районField;
            }
            set
            {
                this.районField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Город
        {
            get
            {
                return this.городField;
            }
            set
            {
                this.городField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаселПункт
        {
            get
            {
                return this.населПунктField;
            }
            set
            {
                this.населПунктField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКТМО
        {
            get
            {
                return this.оКТМОField;
            }
            set
            {
                this.оКТМОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum МестоТипПризнМесто
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведРодитТипПрМестоРожден
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведРодитТипПрУдЛичнФЛ
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведРодитТипПрАдрМЖ
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public partial class СведСвидетТип
    {

        private object itemField;

        private object item1Field;

        private object item2Field;

        private СведСвидетТипТипСвидет типСвидетField;

        /// <summary>
        /// СерияСвидет
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ПрСерияСвидет", typeof(СведСвидетТипПрСерияСвидет))]
        [System.Xml.Serialization.XmlElementAttribute("СерияСвидет", typeof(string))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <summary>
        /// НомерСвидет
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("НомерСвидет", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ПрНомерСвидет", typeof(СведСвидетТипПрНомерСвидет))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <summary>
        /// ДатаВыдСвидет
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ДатаВыдСвидет", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("ДатаВыдСвидетДок", typeof(ДатаДокТип))]
        [System.Xml.Serialization.XmlElementAttribute("ПрДатаВыдСвидет", typeof(СведСвидетТипПрДатаВыдСвидет))]
        public object Item2
        {
            get
            {
                return this.item2Field;
            }
            set
            {
                this.item2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СведСвидетТипТипСвидет ТипСвидет
        {
            get
            {
                return this.типСвидетField;
            }
            set
            {
                this.типСвидетField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведСвидетТипПрСерияСвидет
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведСвидетТипПрНомерСвидет
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведСвидетТипПрДатаВыдСвидет
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/types/4.0.1")]
    public enum СведСвидетТипТипСвидет
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public partial class ROGDINFResponseСведОтветАГССведРегРождПрдСведРег
    {

        private object itemField;

        private ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРоды сведРодыField;

        private ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемся сведРодившемсяField;

        private object item1Field;

        private object item2Field;

        private object item3Field;

        private object item4Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрСчетМатер", typeof(ROGDINFResponseСведОтветАГССведРегРождПрдСведРегПрСчетМатер))]
        [System.Xml.Serialization.XmlElementAttribute("СчетМатер", typeof(string), DataType = "integer")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРоды СведРоды
        {
            get
            {
                return this.сведРодыField;
            }
            set
            {
                this.сведРодыField = value;
            }
        }

        /// <remarks/>
        public ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемся СведРодившемся
        {
            get
            {
                return this.сведРодившемсяField;
            }
            set
            {
                this.сведРодившемсяField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрМать", typeof(ROGDINFResponseСведОтветАГССведРегРождПрдСведРегПрМать))]
        [System.Xml.Serialization.XmlElementAttribute("СведМать", typeof(СведРодитТип))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрОтец", typeof(ROGDINFResponseСведОтветАГССведРегРождПрдСведРегПрОтец))]
        [System.Xml.Serialization.XmlElementAttribute("СведОтец", typeof(СведРодитТип))]
        public object Item2
        {
            get
            {
                return this.item2Field;
            }
            set
            {
                this.item2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрСведДокОснОтец", typeof(ROGDINFResponseСведОтветАГССведРегРождПрдСведРегПрСведДокОснОтец))]
        [System.Xml.Serialization.XmlElementAttribute("СведДокОснОтец", typeof(СведДокОснТип))]
        public object Item3
        {
            get
            {
                return this.item3Field;
            }
            set
            {
                this.item3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрСведДокРод", typeof(ROGDINFResponseСведОтветАГССведРегРождПрдСведРегПрСведДокРод))]
        [System.Xml.Serialization.XmlElementAttribute("СведДокРод", typeof(СведДокТип))]
        public object Item4
        {
            get
            {
                return this.item4Field;
            }
            set
            {
                this.item4Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождПрдСведРегПрСчетМатер
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public partial class ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРоды
    {

        private string числоРодДетейField;

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string ЧислоРодДетей
        {
            get
            {
                return this.числоРодДетейField;
            }
            set
            {
                this.числоРодДетейField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПрСчет", typeof(ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодыПрСчет))]
        [System.Xml.Serialization.XmlElementAttribute("Счет", typeof(string), DataType = "integer")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодыПрСчет
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public partial class ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемся
    {

        private object itemField;

        private object item1Field;

        private ФИОПрТип фИОРождField;

        private object item2Field;

        private object item3Field;

        private string сНИЛСField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ЖивМертв", typeof(ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемсяЖивМертв))]
        [System.Xml.Serialization.XmlElementAttribute("ПрЖивМертв", typeof(ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемсяПрЖивМертв))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Пол", typeof(ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемсяПол))]
        [System.Xml.Serialization.XmlElementAttribute("ПрПол", typeof(ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемсяПрПол))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }

        /// <remarks/>
        public ФИОПрТип ФИОРожд
        {
            get
            {
                return this.фИОРождField;
            }
            set
            {
                this.фИОРождField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДатаРождДок", typeof(ДатаДокТип))]
        [System.Xml.Serialization.XmlElementAttribute("ДатаРождКаленд", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("ПрДатаРожд", typeof(ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемсяПрДатаРожд))]
        public object Item2
        {
            get
            {
                return this.item2Field;
            }
            set
            {
                this.item2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("МестоРожден", typeof(МестоТип))]
        [System.Xml.Serialization.XmlElementAttribute("ПрМестоРожден", typeof(ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемсяПрМестоРожден))]
        public object Item3
        {
            get
            {
                return this.item3Field;
            }
            set
            {
                this.item3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СНИЛС
        {
            get
            {
                return this.сНИЛСField;
            }
            set
            {
                this.сНИЛСField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемсяЖивМертв
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемсяПрЖивМертв
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемсяПол
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемсяПрПол
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемсяПрДатаРожд
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождПрдСведРегСведРодившемсяПрМестоРожден
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождПрдСведРегПрМать
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождПрдСведРегПрОтец
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождПрдСведРегПрСведДокОснОтец
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождПрдСведРегПрСведДокРод
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГССведРегРождРазделЕГР
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseСведОтветАГСРезОбраб
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-zags-rogdinf/root/112-51/4.0.1")]
    public enum ROGDINFResponseТипАГСЗапрос
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
    }
}
