//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

//
// This source code was auto-generated by xsd, Version=4.8.3928.0.
//


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mserus.ru/mse/disabilityExtract/1.0.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://mserus.ru/mse/disabilityExtract/1.0.0", IsNullable=false)]
public partial class DisabilityExtractResponse {

    private string buroFullNameField;


    private string seriesField;


    private string numberField;


    private string actNumberField;


    private System.DateTime actDateField;


    private string lastNameField;


    private string firstNameField;


    private string secondNameField;


    private string addressField;


    private bool isFirstTimeField;


    private System.DateTime disabilityDateField;


    private int disabilityGroupIdField;


    private string disabilityGroupNameField;


    private System.Nullable<int> disabilityReasonIdField;


    private string disabilityReasonNameField;


    private System.Nullable<bool> isVisionImpairedField;


    private System.Nullable<System.DateTime> disabilityEndDateField;


    private System.Nullable<System.DateTime> nextExamDateField;


    private DisabilityExtractResponseExaminationMissReason examinationMissReasonField;



    private DisabilityExtractResponsePrevDisability prevDisabilityField;


    private System.DateTime issueDateField;


    private string buroChiefLastNameField;


    private string buroChiefFirstNameField;


    private string buroChiefSecondNameField;

    /// <summary>
    ///     Наименование бюро МСЭ (экспертного состава Главного бюро), выдавшего справку об инвалидности
    /// </summary>
    public string BuroFullName {
        get {
            return this.buroFullNameField;
        }
        set {
            this.buroFullNameField = value;
        }
    }

    /// <summary>
    ///     Серия справки
    /// </summary>
    public string Series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }

    /// <summary>
    ///     Номер справки
    /// </summary>
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }

    /// <summary>
    ///     Номер акта МСЭ
    /// </summary>
    public string ActNumber {
        get {
            return this.actNumberField;
        }
        set {
            this.actNumberField = value;
        }
    }

    /// <summary>
    ///     Дата акта
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ActDate {
        get {
            return this.actDateField;
        }
        set {
            this.actDateField = value;
        }
    }

    /// <summary>
    ///     Фамилия гражданина
    /// </summary>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }

    /// <summary>
    ///     Имя гражданина
    /// </summary>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }

    /// <summary>
    ///     Отчество гражданина
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SecondName {
        get {
            return this.secondNameField;
        }
        set {
            this.secondNameField = value;
        }
    }

    /// <summary>
    ///     Адрес места жительства
    /// </summary>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }

    /// <summary>
    ///     Впервые или повторно установлена инвалидность
    /// </summary>
    public bool IsFirstTime {
        get {
            return this.isFirstTimeField;
        }
        set {
            this.isFirstTimeField = value;
        }
    }

    /// <summary>
    ///     Дата установления инвалидности
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DisabilityDate {
        get {
            return this.disabilityDateField;
        }
        set {
            this.disabilityDateField = value;
        }
    }

    /// <summary>
    ///     Идентификатор группы инвалидности
    /// </summary>
    public int DisabilityGroupId {
        get {
            return this.disabilityGroupIdField;
        }
        set {
            this.disabilityGroupIdField = value;
        }
    }

    /// <summary>
    ///     Группа инвалидности
    /// </summary>
    public string DisabilityGroupName {
        get {
            return this.disabilityGroupNameField;
        }
        set {
            this.disabilityGroupNameField = value;
        }
    }

    /// <summary>
    ///     Идентификатор причины инвалидности
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> DisabilityReasonId {
        get {
            return this.disabilityReasonIdField;
        }
        set {
            this.disabilityReasonIdField = value;
        }
    }

    /// <summary>
    ///     Формулировка причины инвалидности
    /// </summary>
    public string DisabilityReasonName {
        get {
            return this.disabilityReasonNameField;
        }
        set {
            this.disabilityReasonNameField = value;
        }
    }

    /// <summary>
    ///     Присутствует ли в справке отметка «Инвалид по зрению»
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsVisionImpaired {
        get {
            return this.isVisionImpairedField;
        }
        set {
            this.isVisionImpairedField = value;
        }
    }

    /// <summary>
    ///     Дата, до которой установлена инвалидность
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> DisabilityEndDate {
        get {
            return this.disabilityEndDateField;
        }
        set {
            this.disabilityEndDateField = value;
        }
    }

    /// <summary>
    ///     Дата очередного освидетельствования
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> NextExamDate {
        get {
            return this.nextExamDateField;
        }
        set {
            this.nextExamDateField = value;
        }
    }

    /// <summary>
    ///     Причина пропуска срока переосвидетельствования за прошлое время. Начало периода (обязательный блок)
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public DisabilityExtractResponseExaminationMissReason ExaminationMissReason {
        get {
            return this.examinationMissReasonField;
        }
        set {
            this.examinationMissReasonField = value;
        }
    }

    /// <summary>
    ///     Сведения об установлении инвалидности за прошлое время (при наличии) (обязательный блок)
    /// </summary>
    public DisabilityExtractResponsePrevDisability PrevDisability {
        get {
            return this.prevDisabilityField;
        }
        set {
            this.prevDisabilityField = value;
        }
    }

    /// <summary>
    ///     Дата выдачи справки об установлении инвалидности
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime IssueDate {
        get {
            return this.issueDateField;
        }
        set {
            this.issueDateField = value;
        }
    }

    /// <summary>
    ///     Фамилия руководителя федерального государственного учреждения медико-социальной экспертизы
    /// </summary>
    public string BuroChiefLastName {
        get {
            return this.buroChiefLastNameField;
        }
        set {
            this.buroChiefLastNameField = value;
        }
    }

    /// <summary>
    ///     Имя руководителя федерального государственного учреждения медико-социальной экспертизы
    /// </summary>
    public string BuroChiefFirstName {
        get {
            return this.buroChiefFirstNameField;
        }
        set {
            this.buroChiefFirstNameField = value;
        }
    }

    /// <summary>
    ///     Отчество руководителя федерального государственного учреждения медико-социальной экспертизы
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string BuroChiefSecondName {
        get {
            return this.buroChiefSecondNameField;
        }
        set {
            this.buroChiefSecondNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mserus.ru/mse/disabilityExtract/1.0.0")]
public partial class DisabilityExtractResponseExaminationMissReason {


    private System.Nullable<System.DateTime> dateFromField;


    private System.Nullable<System.DateTime> dateToField;


    private System.Nullable<bool> isValidField;

    /// <summary>
    ///     Инвалидность за предыдущий период. Дата с.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> DateFrom {
        get {
            return this.dateFromField;
        }
        set {
            this.dateFromField = value;
        }
    }

    /// <summary>
    ///     Причина пропуска срока переосвидетельствования за прошлое время. Дата по (Окончание периода)
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> DateTo {
        get {
            return this.dateToField;
        }
        set {
            this.dateToField = value;
        }
    }

    /// <summary>
    ///     Причина пропуска срока переосвидетельствования за прошлое время признана/не признана уважительной
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsValid {
        get {
            return this.isValidField;
        }
        set {
            this.isValidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mserus.ru/mse/disabilityExtract/1.0.0")]
public partial class DisabilityExtractResponsePrevDisability {


    private System.Nullable<System.DateTime> dateFromField;


    private System.Nullable<System.DateTime> dateToField;


    private System.Nullable<bool> isPrevDisabilitySetField;

    /// <summary>
    ///     Инвалидность за предыдущий период. Дата с. (Начало периода)
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> DateFrom {
        get {
            return this.dateFromField;
        }
        set {
            this.dateFromField = value;
        }
    }

    /// <summary>
    ///     Инвалидность за предыдущий период. Дата по. (Окончание периода)
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> DateTo {
        get {
            return this.dateToField;
        }
        set {
            this.dateToField = value;
        }
    }

    /// <summary>
    ///
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsPrevDisabilitySet {
        get {
            return this.isPrevDisabilitySetField;
        }
        set {
            this.isPrevDisabilitySetField = value;
        }
    }
}
