//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

//
// This source code was auto-generated by xsd, Version=4.7.3081.0.
//

namespace RestChild.Comon.Exchange.Snils
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://kvs.pfr.com/snils-by-additionalData/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://kvs.pfr.com/snils-by-additionalData/1.0.1",
        IsNullable = false)]
    public partial class SnilsByAdditionalDataResponse
    {

        private string familyNameField;

        private string firstNameField;

        private string patronymicField;

        private string snilsField;

        private System.DateTime birthDateField;

        private GenderType genderField;

        private BirthPlaceType birthPlaceField;

        private object itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace =
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        public string FamilyName
        {
            get { return this.familyNameField; }
            set { this.familyNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace =
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        public string FirstName
        {
            get { return this.firstNameField; }
            set { this.firstNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace =
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        public string Patronymic
        {
            get { return this.patronymicField; }
            set { this.patronymicField = value; }
        }

        /// <remarks/>
        public string Snils
        {
            get { return this.snilsField; }
            set { this.snilsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime BirthDate
        {
            get { return this.birthDateField; }
            set { this.birthDateField = value; }
        }

        /// <remarks/>
        public GenderType Gender
        {
            get { return this.genderField; }
            set { this.genderField = value; }
        }

        /// <remarks/>
        public BirthPlaceType BirthPlace
        {
            get { return this.birthPlaceField; }
            set { this.birthPlaceField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PfrIdentificationDocument", typeof(IdentificationDocumentType),
            Namespace = "http://common.kvs.pfr.com/1.0.0")]
        [System.Xml.Serialization.XmlElementAttribute("BirthCertificate", typeof(SovietPassportType), Namespace =
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlElementAttribute("DrivingLicenseRF", typeof(DrivingLicenseRFType), Namespace =
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlElementAttribute("ForeignPassport", typeof(NotRestrictedDocumentType), Namespace =
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlElementAttribute("Form9Certificate", typeof(NotRestrictedDocumentType), Namespace =
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlElementAttribute("InternationalPassportRF", typeof(InternationalPassportRFType),
            Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlElementAttribute("MilitaryPassport", typeof(MilitaryPassportDocumentType),
            Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlElementAttribute("PassportLossCertificate", typeof(NotRestrictedDocumentType),
            Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlElementAttribute("PassportRF", typeof(PassportRFType), Namespace =
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlElementAttribute("ReleaseCertificate", typeof(NotRestrictedDocumentType),
            Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlElementAttribute("ResidencePermitRF", typeof(InternationalPassportRFType),
            Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlElementAttribute("SailorPassport", typeof(MilitaryPassportDocumentType),
            Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlElementAttribute("SovietPassport", typeof(SovietPassportType), Namespace =
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlElementAttribute("TemporaryIdentityCardRF", typeof(NotRestrictedDocumentType),
            Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://common.kvs.pfr.com/1.0.0")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
    public enum GenderType
    {

        /// <remarks/>
        Male,

        /// <remarks/>
        Female,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://common.kvs.pfr.com/1.0.0")]
    public partial class BirthPlaceType
    {

        private string placeTypeField;

        private string settlementField;

        private string districtField;

        private string regionField;

        private string countryField;

        /// <remarks/>
        public string PlaceType
        {
            get { return this.placeTypeField; }
            set { this.placeTypeField = value; }
        }

        /// <remarks/>
        public string Settlement
        {
            get { return this.settlementField; }
            set { this.settlementField = value; }
        }

        /// <remarks/>
        public string District
        {
            get { return this.districtField; }
            set { this.districtField = value; }
        }

        /// <remarks/>
        public string Region
        {
            get { return this.regionField; }
            set { this.regionField = value; }
        }

        /// <remarks/>
        public string Country
        {
            get { return this.countryField; }
            set { this.countryField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://common.kvs.pfr.com/1.0.0")]
    public partial class IdentificationDocumentType
    {

        private string typeField;

        private NotRestrictedDocumentType documentField;

        /// <remarks/>
        public string Type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        public NotRestrictedDocumentType Document
        {
            get { return this.documentField; }
            set { this.documentField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute("ForeignPassport",
        Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", IsNullable = false)]
    public partial class NotRestrictedDocumentType
    {

        private string seriesField;

        private string numberField;

        private System.DateTime issueDateField;

        private string issuerField;

        /// <remarks/>
        public string Series
        {
            get { return this.seriesField; }
            set { this.seriesField = value; }
        }

        /// <remarks/>
        public string Number
        {
            get { return this.numberField; }
            set { this.numberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime IssueDate
        {
            get { return this.issueDateField; }
            set { this.issueDateField = value; }
        }

        /// <remarks/>
        public string Issuer
        {
            get { return this.issuerField; }
            set { this.issuerField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute("DrivingLicenseRF",
        Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", IsNullable = false)]
    public partial class DrivingLicenseRFType
    {

        private string seriesField;

        private string numberField;

        private System.DateTime issueDateField;

        private string issuerField;

        /// <remarks/>
        public string Series
        {
            get { return this.seriesField; }
            set { this.seriesField = value; }
        }

        /// <remarks/>
        public string Number
        {
            get { return this.numberField; }
            set { this.numberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime IssueDate
        {
            get { return this.issueDateField; }
            set { this.issueDateField = value; }
        }

        /// <remarks/>
        public string Issuer
        {
            get { return this.issuerField; }
            set { this.issuerField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute("SovietPassport",
        Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", IsNullable = false)]
    public partial class SovietPassportType
    {

        private string seriesField;

        private string numberField;

        private System.DateTime issueDateField;

        private string issuerField;

        /// <remarks/>
        public string Series
        {
            get { return this.seriesField; }
            set { this.seriesField = value; }
        }

        /// <remarks/>
        public string Number
        {
            get { return this.numberField; }
            set { this.numberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime IssueDate
        {
            get { return this.issueDateField; }
            set { this.issueDateField = value; }
        }

        /// <remarks/>
        public string Issuer
        {
            get { return this.issuerField; }
            set { this.issuerField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute("MilitaryPassport",
        Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", IsNullable = false)]
    public partial class MilitaryPassportDocumentType
    {

        private string seriesField;

        private string numberField;

        private System.DateTime issueDateField;

        private string issuerField;

        /// <remarks/>
        public string Series
        {
            get { return this.seriesField; }
            set { this.seriesField = value; }
        }

        /// <remarks/>
        public string Number
        {
            get { return this.numberField; }
            set { this.numberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime IssueDate
        {
            get { return this.issueDateField; }
            set { this.issueDateField = value; }
        }

        /// <remarks/>
        public string Issuer
        {
            get { return this.issuerField; }
            set { this.issuerField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute("ResidencePermitRF",
        Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", IsNullable = false)]
    public partial class InternationalPassportRFType
    {

        private string seriesField;

        private string numberField;

        private System.DateTime issueDateField;

        private string issuerField;

        /// <remarks/>
        public string Series
        {
            get { return this.seriesField; }
            set { this.seriesField = value; }
        }

        /// <remarks/>
        public string Number
        {
            get { return this.numberField; }
            set { this.numberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime IssueDate
        {
            get { return this.issueDateField; }
            set { this.issueDateField = value; }
        }

        /// <remarks/>
        public string Issuer
        {
            get { return this.issuerField; }
            set { this.issuerField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute("PassportRF",
        Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", IsNullable = false)]
    public partial class PassportRFType
    {

        private string seriesField;

        private string numberField;

        private System.DateTime issueDateField;

        private string issuerField;

        /// <remarks/>
        public string Series
        {
            get { return this.seriesField; }
            set { this.seriesField = value; }
        }

        /// <remarks/>
        public string Number
        {
            get { return this.numberField; }
            set { this.numberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime IssueDate
        {
            get { return this.issueDateField; }
            set { this.issueDateField = value; }
        }

        /// <remarks/>
        public string Issuer
        {
            get { return this.issuerField; }
            set { this.issuerField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://common.kvs.pfr.com/1.0.0", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        PfrIdentificationDocument,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:BirthCertificate")]
        BirthCertificate,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:DrivingLicenseRF")]
        DrivingLicenseRF,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:ForeignPassport")]
        ForeignPassport,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:Form9Certificate")]
        Form9Certificate,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:InternationalPassportRF" +
            "")]
        InternationalPassportRF,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:MilitaryPassport")]
        MilitaryPassport,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:PassportLossCertificate" +
            "")]
        PassportLossCertificate,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:PassportRF")]
        PassportRF,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:ReleaseCertificate")]
        ReleaseCertificate,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:ResidencePermitRF")]
        ResidencePermitRF,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:SailorPassport")]
        SailorPassport,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:SovietPassport")]
        SovietPassport,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(
            "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1:TemporaryIdentityCardRF" +
            "")]
        TemporaryIdentityCardRF,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute("AttachmentRef",
        Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", IsNullable = false)]
    public partial class AttachmentRefType
    {

        private string attachmentIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string attachmentId
        {
            get { return this.attachmentIdField; }
            set { this.attachmentIdField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute("PrimaryIdentityDocument",
        Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", IsNullable = false)]
    public partial class PrimaryIdentityDocumentType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ForeignPassport", typeof(NotRestrictedDocumentType))]
        [System.Xml.Serialization.XmlElementAttribute("PassportRF", typeof(PassportRFType))]
        [System.Xml.Serialization.XmlElementAttribute("ResidencePermitRF", typeof(InternationalPassportRFType))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1")]
    [System.Xml.Serialization.XmlRootAttribute("IdentityDocument",
        Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", IsNullable = false)]
    public partial class AnyIdentityDocumentType
    {

        private object itemField;

        private ItemChoiceType1 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BirthCertificate", typeof(SovietPassportType))]
        [System.Xml.Serialization.XmlElementAttribute("DrivingLicenseRF", typeof(DrivingLicenseRFType))]
        [System.Xml.Serialization.XmlElementAttribute("ForeignPassport", typeof(NotRestrictedDocumentType))]
        [System.Xml.Serialization.XmlElementAttribute("Form9Certificate", typeof(NotRestrictedDocumentType))]
        [System.Xml.Serialization.XmlElementAttribute("InternationalPassportRF", typeof(InternationalPassportRFType))]
        [System.Xml.Serialization.XmlElementAttribute("MilitaryPassport", typeof(MilitaryPassportDocumentType))]
        [System.Xml.Serialization.XmlElementAttribute("PassportLossCertificate", typeof(NotRestrictedDocumentType))]
        [System.Xml.Serialization.XmlElementAttribute("PassportRF", typeof(PassportRFType))]
        [System.Xml.Serialization.XmlElementAttribute("ReleaseCertificate", typeof(NotRestrictedDocumentType))]
        [System.Xml.Serialization.XmlElementAttribute("ResidencePermitRF", typeof(InternationalPassportRFType))]
        [System.Xml.Serialization.XmlElementAttribute("SailorPassport", typeof(MilitaryPassportDocumentType))]
        [System.Xml.Serialization.XmlElementAttribute("SovietPassport", typeof(SovietPassportType))]
        [System.Xml.Serialization.XmlElementAttribute("TemporaryIdentityCardRF", typeof(NotRestrictedDocumentType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1",
        IncludeInSchema = false)]
    public enum ItemChoiceType1
    {

        /// <remarks/>
        BirthCertificate,

        /// <remarks/>
        DrivingLicenseRF,

        /// <remarks/>
        ForeignPassport,

        /// <remarks/>
        Form9Certificate,

        /// <remarks/>
        InternationalPassportRF,

        /// <remarks/>
        MilitaryPassport,

        /// <remarks/>
        PassportLossCertificate,

        /// <remarks/>
        PassportRF,

        /// <remarks/>
        ReleaseCertificate,

        /// <remarks/>
        ResidencePermitRF,

        /// <remarks/>
        SailorPassport,

        /// <remarks/>
        SovietPassport,

        /// <remarks/>
        TemporaryIdentityCardRF,
    }
}
